window.trackerDefaults = {
  '4 Maps': 'tokens',
  '5 Maps': 'tokens',
  '6 Maps': 'tokens',
  '7 Maps': 'tokens',
  '4 Compasses': 'tokens',
  '5 Compasses': 'tokens',
  '6 Compasses': 'tokens',
  '7 Compasses': 'tokens',
  '2 Boss Keys': 'tokens',
  '3 Boss Keys': 'tokens',
  'Map & Compass in Deku Tree': 'none',
  'Map & Compass in Jabu-Jabu': 'none',
  "Map & Compass in Dodongo's Cavern": 'none',
  'Map & Compass in Forest Temple': 'none',
  'Map & Compass in Fire Temple': 'none',
  'Map & Compass in Water Temple': 'none',
  'Map & Compass in Shadow Temple': 'none',
  'Map & Compass in Spirit Temple': 'none',
  'Map & Compass in Bottom of the Well': 'none',
  'Map & Compass in Ice Cavern': 'none',
  '3 Swords': 'tokens',
  '3 Shields': 'tokens',
  '3 Tunics': 'tokens',
  '3 Boots': 'tokens',
  '3 Swords & 3 Shields': 'tokens',
  '3 Swords & 3 Tunics': 'tokens',
  '3 Swords & 3 Boots': 'tokens',
  '3 Shields & 3 Tunics': 'tokens',
  '3 Shields & 3 Boots': 'tokens',
  '3 Tunics & 3 Boots': 'tokens',
  '3 Swords, Tunics, Boots, and Shields': 'tokens',
  'Two Fairy Spells': 'tokens',
  'All 3 Elemental Arrows': 'tokens',
  '3 Songs': 'tokens',
  '4 Songs': 'tokens',
  '6 Songs': 'tokens',
  '7 Songs': 'tokens',
  '8 Songs': 'tokens',
  '9 Songs': 'tokens',
  '10 Songs': 'tokens',
  '5 Magic Beans': 'counter',
  '7 Magic Beans': 'counter',
  '9 Magic Beans': 'counter',
  'All 3 Kokiri Forest area Skulltulas': 'counter',
  'All 4 Lost Woods area Skulltulas': 'counter',
  'Both Hyrule Field area Skulltulas': 'counter',
  'All 4 Market area Skulltulas': 'counter',
  'All 4 Lon-Lon Ranch area Skulltulas': 'none',
  'All 8 Kakariko area Skulltulas': 'counter',
  'All 8 Death Mountain area Skulltulas': 'counter',
  "All 8 Zora's Domain area Skulltulas": 'counter',
  '3 Lake Hylia Skulltulas': 'none',
  'All 5 Lake Hylia Skulltulas': 'counter',
  'All 4 Gerudo Valley area Skulltulas': 'counter',
  "Both Gerudo's Fortress area Skulltulas": 'none',
  'All 4 Wasteland/ Colossus area Skulltulas': 'counter',
  'All 4 Skulltulas in Deku Tree': 'none',
  "All 5 Skulltulas in Dodongo's Cavern": 'none',
  'All 4 Skulltulas in Jabu-Jabu': 'none',
  'All 5 Skulltulas in Forest Temple': 'none',
  'All 5 Skulltulas in Fire Temple': 'none',
  'All 5 Skulltulas in Water Temple': 'none',
  '3 Skulltulas in Water Temple': 'none',
  'All 5 Skulltulas in Shadow Temple': 'none',
  '4 Skulltulas in Shadow Temple': 'none',
  'All 5 Skulltulas in Spirit Temple': 'none',
  'All 3 Skulltulas in Ice Cavern': 'none',
  'All 3 Skulltulas in Bottom of the Well': 'none',
  '15 Different Skulltulas': 'counter',
  'Stone of Agony': 'counter',
  '1 Skulltula from each Child Dungeon': 'tokens',
  '1 Skulltula from each Adult Dungeon': 'tokens',
  '1 Unused Small Key in each Adult Dungeon': 'tokens',
  '4 Unused Keys in Forest Temple': 'none',
  '3 Unused Keys in Gerudo Training Grounds': 'none',
  '4 Unused Keys in Gerudo Training Grounds': 'none',
  '5 Unused Keys in Gerudo Training Grounds': 'none',
  '6 Unused Keys in Gerudo Training Grounds': 'none',
  '7 Different Unused Keys in Gerudo Training Grounds': 'none',
  '8 Different Unused Keys in Gerudo Training Grounds': 'none',
  '9 Different Unused Keys in Gerudo Training Grounds': 'none',
  'Obtain all 5 Small Keys in Forest Temple': 'none',
  'Obtain all 8 Small Keys in Fire Temple': 'none',
  'Obtain all 5 Small Keys in Shadow Temple': 'none',
  'Both HPs in Lost Woods': 'counter',
  'Both HPs in Death Mountain Crater': 'none',
  '5 Zora area HPs': 'counter',
  'Both Gerudo Valley HPs': 'none',
  'Defeat 4 Different Iron Knuckles': 'counter',
  'Free all 9 Gorons in Fire Temple': 'none',
  'Clear 4 Silver Rupee Rooms': 'counter',
  'Clear 8 Silver Rupee Rooms': 'counter',
  'Clear 10 Silver Rupee Rooms': 'counter',
  'Open 3 Gold Rupee Chests': 'counter',
  'Open 5 Gold Rupee Chests': 'counter',
  'Open All 6 Gold Rupee Chests': 'counter',
  'Open 2 Boss Key Doors': 'tokens',
  'Open 3 Boss Key Doors': 'tokens',
  '20 Different Skulltulas': 'counter',
  '30 Different Skulltulas': 'counter',
  'Plant 5 Magic Beans': 'counter',
  'All 4 Child Skulltulas in Zora\'s Domain': 'counter',
  'All 4 Adult Skulltulas in Zora\'s Domain': 'counter',
  '7 Different Bottled Contents': 'tokens'
};
