window.trackerDefaults = {
  '4 Maps': 'tokens',
  'マップ4つ': 'tokens',
  '5 Maps': 'tokens',
  'マップ5つ': 'tokens',
  '6 Maps': 'tokens',
  'マップ6つ': 'tokens',
  '7 Maps': 'tokens',
  'マップ7つ': 'tokens',
  '4 Compasses': 'tokens',
  'コンパス4つ': 'tokens',
  '5 Compasses': 'tokens',
  'コンパス5つ': 'tokens',
  '6 Compasses': 'tokens',
  'コンパス6つ': 'tokens',
  '7 Compasses': 'tokens',
  'コンパス7つ': 'tokens',
  '2 Boss Keys': 'tokens',
  'ボス部屋の鍵2つ': 'tokens',
  '3 Boss Keys': 'tokens',
  'ボス部屋の鍵3つ': 'tokens',
  'Map & Compass in Deku Tree': 'none',
  'デクの樹様の中のマップとコンパス': 'none',
  'Map & Compass in Jabu-Jabu': 'none',
  'ジャブジャブ様のお腹のマップとコンパス': 'none',
  'Map & Compass in Dodongo\'s Cavern': 'none',
  'ドドンゴの洞窟のマップとコンパス': 'none',
  'Map & Compass in Forest Temple': 'none',
  '森の神殿のマップとコンパス': 'none',
  'Map & Compass in Fire Temple': 'none',
  '炎の神殿のマップとコンパス': 'none',
  'Map & Compass in Water Temple': 'none',
  '水の神殿のマップとコンパス': 'none',
  'Map & Compass in Shadow Temple': 'none',
  '闇の神殿のマップとコンパス': 'none',
  'Map & Compass in Spirit Temple': 'none',
  '魂の神殿のマップとコンパス': 'none',
  'Map & Compass in Bottom of the Well': 'none',
  '井戸の底のマップとコンパス': 'none',
  'Map & Compass in Ice Cavern': 'none',
  '氷の洞窟のマップとコンパス': 'none',
  '3 Shields': 'tokens',
  '盾3種': 'tokens',
  '3 Tunics': 'tokens',
  '服3種': 'tokens',
  '3 Boots': 'tokens',
  '靴3種': 'tokens',
  '3 Swords & 3 Shields': 'tokens',
  '剣3種、盾3種': 'tokens',
  '3 Swords & 3 Tunics': 'tokens',
  '剣3種、服3種': 'tokens',
  '3 Swords & 3 Boots': 'tokens',
  '剣3種、靴3種': 'tokens',
  '3 Shields & 3 Tunics': 'tokens',
  '盾3種、服3種': 'tokens',
  '3 Shields & 3 Boots': 'tokens',
  '盾3種、靴3種': 'tokens',
  '3 Tunics & 3 Boots': 'tokens',
  '服3種、靴3種': 'tokens',
  '3 Swords, Tunics, Boots, and Shields': 'tokens',
  '剣3種、盾3種、服3種、靴3種': 'tokens',
  'Two Fairy Spells': 'tokens',
  '魔法のアイテム2つ': 'tokens',
  'All 3 Elemental Arrows': 'tokens',
  '魔法矢3つ': 'tokens',
  '3 Songs': 'tokens',
  '歌3つ以上': 'tokens',
  '4 Songs': 'tokens',
  '歌4つ以上': 'tokens',
  '6 Songs': 'tokens',
  '歌6つ以上': 'tokens',
  '7 Songs': 'tokens',
  '歌7つ以上': 'tokens',
  '8 Songs': 'tokens',
  '歌8つ以上': 'tokens',
  '9 Songs': 'tokens',
  '歌9つ以上': 'tokens',
  '10 Songs': 'tokens',
  '歌10つ以上': 'tokens',
  '5 Magic Beans': 'counter',
  '魔法のマメ5つ以上': 'counter',
  '7 Magic Beans': 'counter',
  '魔法のマメ7つ以上': 'counter',
  'All 3 Kokiri Forest area Skulltulas': 'counter',
  'コキリの森エリアの黄金のスタルチュラ3匹': 'counter',
  'All 4 Lost Woods area Skulltulas': 'counter',
  '迷いの森エリアの黄金のスタルチュラ4匹': 'counter',
  'Both Hyrule Field area Skulltulas': 'counter',
  'ハイラル平原エリアの黄金ノスタルチュラ2匹': 'counter',
  'All 4 Market area Skulltulas': 'counter',
  '城下町エリアの黄金のスタルチュラ4匹': 'counter',
  'All 4 Lon-Lon Ranch area Skulltulas': 'none',
  'ロンロン牧場エリアの黄金のスタルチュラ4匹': 'none',
  'All 8 Kakariko area Skulltulas': 'counter',
  'カカリコ村エリアの黄金のスタルチュラ8匹': 'counter',
  'All 8 Death Mountain area Skulltulas': 'counter',
  'デスマウンテンエリアの黄金のスタルチュラ8匹': 'counter',
  'All 8 Zora\'s Domain area Skulltulas': 'counter',
  'ゾーラの里エリアの黄金のスタルチュラ8匹': 'counter',
  '3 Lake Hylia Skulltulas': 'none',
  'ハイリア湖畔エリアの黄金のスタルチュラ3匹以上': 'none',
  'All 5 Lake Hylia Skulltulas': 'counter',
  'ハイリア湖畔エリアの黄金のスタルチュラ5匹': 'counter',
  'All 4 Gerudo Valley area Skulltulas': 'counter',
  'ゲルドの谷エリアの黄金のスタルチュラ4匹': 'counter',
  'Both Gerudo\'s Fortress area Skulltulas': 'none',
  'ゲルドの砦の黄金のスタルチュラ2匹': 'none',
  'All 4 Wasteland/ Colossus area Skulltulas': 'counter',
  '幻影の砂漠・巨大邪神像エリアの黄金のスタルチュラ4匹': 'counter',
  'All 4 Skulltulas in Deku Tree': 'none',
  'デクの樹様の中の黄金のスタルチュラ4匹': 'none',
  'All 5 Skulltulas in Dodongo\'s Cavern': 'none',
  'ドドンゴの洞窟の黄金のスタルチュラ5匹': 'none',
  'All 4 Skulltulas in Jabu-Jabu': 'none',
  'ジャブジャブ様のお腹の黄金のスタルチュラ4匹': 'none',
  'All 5 Skulltulas in Forest Temple': 'none',
  '森の神殿の黄金のスタルチュラ5匹': 'none',
  'All 5 Skulltulas in Fire Temple': 'none',
  '炎の神殿の黄金のスタルチュラ5匹': 'none',
  'All 5 Skulltulas in Water Temple': 'none',
  '水の神殿の黄金のスタルチュラ5匹': 'none',
  '3 Skulltulas in Water Temple': 'none',
  '水の神殿の黄金のスタルチュラ3匹以上': 'none',
  'All 5 Skulltulas in Shadow Temple': 'none',
  '闇の神殿の黄金のスタルチュラ5匹': 'none',
  '4 Skulltulas in Shadow Temple': 'none',
  '闇の神殿の黄金のスタルチュラ4匹以上': 'none',
  'All 5 Skulltulas in Spirit Temple': 'none',
  '魂の神殿の黄金のスタルチュラ5匹': 'none',
  'All 3 Skulltulas in Ice Cavern': 'none',
  '氷の洞窟の黄金のスタルチュラ3匹': 'none',
  'All 3 Skulltulas in Bottom of the Well': 'none',
  '井戸の底の黄金のスタルチュラ3匹': 'none',
  '15 Different Skulltulas': 'counter',
  'スタルチュラのしるし15個(増殖禁止)': 'counter',
  'Stone of Agony': 'counter',
  'もだえ石': 'counter',
  '1 Skulltula from each Child Dungeon': 'tokens',
  '全ての子供ダンジョンからスタルチュラ最低1匹ずつ': 'tokens',
  '1 Skulltula from each Adult Dungeon': 'tokens',
  '全ての大人ダンジョンからスタルチュラ最低1匹ずつ': 'tokens',
  '1 Unused Small Key in each Adult Dungeon': 'tokens',
  '全ての大人のダンジョンから未使用の鍵最低1つずつ': 'tokens',
  '4 Unused Keys in Forest Temple': 'none',
  '森の神殿の未使用の小さな鍵4つ': 'none',
  '3 Unused Keys in Gerudo Training Grounds': 'none',
  'ゲルドの修練場の未使用の鍵3つ': 'none',
  '4 Unused Keys in Gerudo Training Grounds': 'none',
  'ゲルドの修練場の未使用の鍵4つ': 'none',
  '5 Unused Keys in Gerudo Training Grounds': 'none',
  'ゲルドの修練場の未使用の鍵5つ': 'none',
  '7 Different Unused Keys in Gerudo Training Grounds': 'none',
  'ゲルドの修練場の未使用の鍵7つ(増殖禁止)': 'none',
  '8 Different Unused Keys in Gerudo Training Grounds': 'none',
  'ゲルドの修練場の未使用の鍵8つ(増殖禁止)': 'none',
  'Obtain all 5 Small Keys in Forest Temple': 'none',
  '森の神殿の小さな鍵の宝箱を5つ全て開ける': 'none',
  'Obtain all 8 Small Keys in Fire Temple': 'none',
  '炎の神殿の小さな鍵の宝箱を8つ全て開ける': 'none',
  'Obtain all 5 Small Keys in Shadow Temple': 'none',
  '闇の神殿の小さな鍵5つ取得': 'none',
  'Both HPs in Lost Woods': 'counter',
  '迷いの森のハートのかけら2つ': 'counter',
  'Both HPs in Death Mountain Crater': 'none',
  'デスマウンテン火口のハートのかけら2つ': 'none',
  '5 Zora area HPs': 'counter',
  'ゾーラエリアのハートのかけら5つ以上': 'counter',
  'Both Gerudo Valley HPs': 'none',
  'ゲルドの谷のハートのかけら2つ': 'none',
  'Defeat 4 Different Iron Knuckles': 'counter',
  'アイアンナックを4体撃破': 'counter',
  'Free all 9 Gorons in Fire Temple': 'none',
  '炎の神殿で9人のゴロンを全員救う': 'none',
  'Clear 4 Silver Rupee Rooms': 'counter',
  '銀ルピー部屋を4箇所攻略': 'counter',
  'Clear 8 Silver Rupee Rooms': 'counter',
  '銀ルピー部屋を8箇所攻略': 'counter',
  'Clear 10 Silver Rupee Rooms': 'counter',
  '銀ルピー部屋を10箇所攻略': 'counter',
  'Open 3 Gold Rupee Chests': 'counter',
  '金ルピーの宝箱を3つ開ける': 'counter',
  'Open 5 Gold Rupee Chests': 'counter',
  '金ルピーの宝箱を5つ開ける': 'counter',
  'Open All 6 Gold Rupee Chests': 'counter',
  '金ルピーの宝箱を6つ開ける': 'counter',
  'Open 2 Boss Key Doors': 'tokens',
  'スカギの扉を2つ開ける': 'tokens',
  'Open 3 Boss Key Doors': 'tokens',
  'ボスカギの扉を3つ開ける': 'tokens',
  '20 Different Skulltulas': 'counter',
  'スタルチュラのしるし20個(増殖禁止)': 'counter',
  '30 Different Skulltulas': 'counter',
  'スタルチュラのしるし30個(増殖禁止)': 'counter',
  'Plant 5 Magic Beans': 'counter',
  '魔法の豆を5つ植える': 'counter',
  '7 Different Bottled Contents': 'tokens',
  'ビンに詰めたアイテム7種類': 'tokens'
};
