import en from "./en.js";

export default {
  locale: "en-short",
  strings: {
    ...en.strings,
    "1 Skulltula from each Adult Dungeon": "Adult dungeon Skulls",
    "1 Skulltula from each Child Dungeon": "Child dungeon Skulls",
    "1 Unused Small Key in each Adult Dungeon":
      "1 unused key in each adult dungeon",
    "10 Songs": "10 songs",
    "15 Different Skulltulas": "15 Skulls",
    "2 Boss Keys": "2 BKs",
    "2 Shields": "2 shields",
    "2 Skulltulas in Lon Lon Ranch": "2 Lon Lon Skulls",
    "2 Unused Keys in Gerudo Training Grounds": "2 GTG keys",
    "20 Deku Sticks": "20 Deku Sticks",
    "20 Different Skulltulas": "20 Skulls",
    "200 Rupees": "200 Rupees",
    "3 Boots": "3 boots",
    "3 Boss Keys": "3 BKs",
    "3 Compasses": "3 Compasses",
    "3 Lake Hylia Skulltulas": "3 Hylia Skulls",
    "3 Maps": "3 maps",
    "3 Shields": "3 shields",
    "3 Shields & 3 Boots": "3 shields & 3 boots",
    "3 Shields & 3 Tunics": "3 shields & 3 tunics",
    "3 Skulltulas in Water Temple": "3 Water Skulls",
    "3 Songs": "3 songs",
    "3 Swords & 3 Boots": "3 swords & 3 boots",
    "3 Swords & 3 Shields": "3 swords & 3 shields",
    "3 Swords & 3 Tunics": "3 swords & 3 tunics",
    "3 Swords, Tunics, Boots, and Shields": "All equipment",
    "3 Tunics": "3 tunics",
    "3 Tunics & 3 Boots": "3 tunics & 3 boots",
    "3 Unused Keys in Gerudo Training Grounds": "3 GTG keys",
    "30 Deku Nuts": "30 Deku Nuts",
    "30 Deku Sticks": "30 Deku Sticks",
    "30 Different Skulltulas": "30 Skulls",
    "37th Heart Piece (Child Fortress)": "37th HP",
    "4 Bottles of Milk": "4 Milk Bottles",
    "4 Compasses": "4 compasses",
    "4 Maps": "4 maps",
    "4 Skulltulas in Shadow Temple": "4 Shadow Skulls",
    "4 Songs": "4 songs",
    "4 Unused Keys in Forest Temple": "4 unused Forest keys",
    "4 Unused Keys in Gerudo Training Grounds": "4 GTG keys",
    "5 Compasses": "5 compasses",
    "5 Hearts": "5 hearts",
    "5 Magic Beans": "5 Magic Beans",
    "5 Maps": "5 maps",
    "5 Top Row Songs": "5 Top Row Songs",
    "5 Unused Keys in Gerudo Training Grounds": "5 GTG keys",
    "5 Zora area HPs": "5 Zora HPs",
    "500 Rupees": "500 Rupees",
    "6 Compasses": "6 compasses",
    "6 Different Unused Keys in Gerudo Training Grounds": "6 GTG keys",
    "6 Hearts": "6 hearts",
    "6 Magic Beans": "6 Magic Beans",
    "6 Maps": "6 maps",
    "6 Songs": "6 songs",
    "6 Unused Keys in Gerudo Training Grounds": "6 GTG keys",
    "7 Compasses": "7 compasses",
    "7 Different Bottled Contents": "7 bottled contents",
    "7 Different Unused Keys in Gerudo Training Grounds": "7 GTG keys",
    "7 Hearts (no duping)": "7 hearts",
    "7 Magic Beans": "7 Magic Beans",
    "7 Maps": "7 maps",
    "7 Songs": "7 songs",
    "8 Different Unused Keys in Gerudo Training Grounds": "8 GTG keys",
    "8 Hearts (no duping)": "8 hearts",
    "8 Magic Beans": "8 Magic Beans",
    "8 Songs": "8 songs",
    "9 Hearts (no duping)": "9 hearts",
    "9 Magic Beans": "9 Magic Beans",
    "9 Songs": "9 songs",
    "99 Rupees": "99 Rupees",
    "Adult's Wallet": "Adult's Wallet",
    "All 3 Child Lake Hylia Skulltulas": "3 child Hylia Skulls",
    "All 3 Elemental Arrows": "3 Elemental Arrows",
    "All 3 Kokiri Forest area Skulltulas": "3 Kokiri Skulls",
    "All 3 Skulltulas in Bottom of the Well": "3 BotW Skulls",
    "All 3 Skulltulas in Ice Cavern": "3 Ice Skulls",
    "All 4 Adult Zora's Domain area Skulltulas": "4 adult Zora Skulls",
    "All 4 Child Zora's Domain area Skulltulas": "4 child Zora Skulls",
    "All 4 Gerudo Valley area Skulltulas": "4 Gerudo Valley Skulls",
    "All 4 Lon Lon Ranch area Skulltulas": "4 Lon Lon Skulls",
    "All 4 Lost Woods area Skulltulas": "4 Lost Woods Skulls",
    "All 4 Market area Skulltulas": "4 Market Skulls",
    "All 4 Skulltulas in Deku Tree": "4 Deku Skulls",
    "All 4 Skulltulas in Jabu-Jabu": "4 Jabu Skulls",
    "All 4 Wasteland/ Colossus area Skulltulas": "4 Wasteland/ Colossus Skulls",
    "All 5 Child Death Mountain area Skulltulas":
      "5 Child Death Mountain Skulls",
    "All 5 Lake Hylia Skulltulas": "5 Hylia Skulls",
    "All 5 Skulltulas in Dodongo's Cavern": "5 DC Skulls",
    "All 5 Skulltulas in Fire Temple": "5 Fire Skulls",
    "All 5 Skulltulas in Forest Temple": "5 Forest Skulls",
    "All 5 Skulltulas in Shadow Temple": "5 Shadow Skulls",
    "All 5 Skulltulas in Spirit Temple": "5 Spirit Skulls",
    "All 5 Skulltulas in Water Temple": "5 Water Skulls",
    "All 7 Child Kakariko area Skulltulas": "7 child Kakariko Skulls",
    "All 8 Death Mountain area Skulltulas": "8 Death Mountain Skulls",
    "All 8 Kakariko area Skulltulas": "8 Kakariko Skulls",
    "All 8 Skulltulas in Bottom of the Well & Shadow Temple": "8 BotW & Shadow Skulls",
    "All 8 Skulltulas in Ice Cavern & Spirit Temple": "8 Ice & Spirit Skulls",
    "All 8 Zora's Domain area Skulltulas": "8 Zora Skulls",
    "All 9 Soft Soil Skulltulas": "9 Soft Soil Skulls",
    "Beat Dodongo's Cavern": "Beat DC",
    "Beat Dodongo's Cavern & Fire Temple": "Beat DC & Fire",
    "Beat Jabu-Jabu's Belly": "Beat Jabu",
    "Beat Jabu-Jabu's Belly & Water Temple": "Beat Jabu & Water",
    "Beat the Deku Tree": "Beat Deku",
    "Beat the Deku Tree & Forest Temple": "Beat Deku & Forest",
    "Beat the Fire Temple": "Beat Fire",
    "Beat the Forest Temple": "Beat Forest",
    "Beat the Shadow Temple": "Beat Shadow",
    "Beat the Spirit Temple": "Beat Spirit",
    "Beat the Water Temple": "Beat Water",
    "Biggoron's Sword": "Biggoron's Sword",
    "Blue Fire": "Blue Fire",
    "Blue Gauntlets": "Blue Gauntlets",
    "Blue Potion": "Blue Potion",
    "Bolero of Fire": "Bolero of Fire",
    "Bomb Bag (30)": "Bomb Bag (30)",
    Boomerang: "Boomerang",
    "Both Child Gerudo Valley area Skulltulas": "2 child Gerudo Valley Skulls",
    "Both Child Kokiri Forest area Skulltulas": "2 child Kokiri Skulls",
    "Both Child Lost Woods area Skulltulas": "2 child Lost Woods Skulls",
    "Both Child Wasteland/ Colossus area Skulltulas":
      "2 child Wasteland/ Colossus Skulls",
    "Both Gerudo Valley HPs": "2 Gerudo Valley HPs",
    "Both Gerudo's Fortress area Skulltulas": "2 Gerudo's Fortress Skulls",
    "Both HPs in Death Mountain Crater": "2 DMC HPs",
    "Both HPs in Lost Woods": "2 Lost Woods HPs",
    "Both Hyrule Field area Skulltulas": "2 Hyrule Field Skulls",
    "Both Rusty Switches in Spirit Temple": "Both rusty switches in Spirit",
    "Bottled Fairy": "Bottled Fairy",
    "Bottled Poe": "Bottled Poe",
    "Bronze Gauntlets": "Bronze Gauntlets",
    "Bullet Bag (40)": "Bullet Bag (40)",
    "Bullet Bag (50)": "Bullet Bag (50)",
    "Clear 10 Silver Rupee Rooms": "10 Silver Rupee Rooms",
    "Clear 4 Silver Rupee Rooms": "4 Silver Rupee Rooms",
    "Clear 8 Silver Rupee Rooms": " 8 Silver Rupee Rooms",
    "Cow in House": "Cow in House",
    "Defeat 10 Different Stalfos": "10 Stalfos",
    "Defeat 4 Different Iron Knuckles": "4 Iron Knuckles",
    "Defeat 5 Different Stalfos": "5 Stalfos",
    "Defeat a Skull Kid": "Skull Kid",
    "Defeat a White Wolfos": "White Wolfos",
    "Defeat all Lizalfos in Dodongo's Cavern": "Lizalfos in DC",
    "Defeat Amy (Green Poe)": "Amy (Green Poe)",
    "Defeat Barinade": "Barinade",
    "Defeat Big Octo": "Big Octo",
    "Defeat Bongo-Bongo": "Bongo",
    "Defeat both Flare Dancers": "Both Flare Dancers",
    "Defeat Dark Link": "Dark Link",
    "Defeat King Dodongo": "King Dodongo",
    "Defeat Meg (Purple Poe)": "Meg (Purple Poe)",
    "Defeat Morpha": "Morpha",
    "Defeat Nabooru-Knuckle": "Nabooru-Knuckle",
    "Defeat Phantom Ganon": "Phantom Ganon",
    "Defeat Queen Gohma": "Queen Gohma",
    "Defeat Twinrova": "Twinrova",
    "Defeat Volvagia": "Volvagia",
    "Desert Colossus HP": "Desert Colossus HP",
    "Din's Fire": "Din's Fire",
    "Double Defense": "Double Defense",
    "Double Magic": "Double Magic",
    "Epona's Song": "Epona's Song",
    "Exactly 20 Deku Sticks": "Exactly 20 Deku Sticks",
    "Exactly 30 Deku Sticks": "Exactly 30 Deku Sticks",
    "Fairy Bow": "Fairy Bow",
    "Fairy Ocarina": "Fairy Ocarina",
    "Fairy Slingshot": "Fairy Slingshot",
    "Farore's Wind": "Farore's Wind",
    "Fill 20 Item Inventory Slots": "20 Inventory Slots",
    "Fill all 4 Bottle Slots": "4 Bottle Slots",
    "Fire Arrows": "Fire Arrows",
    "Fire Medallion": "Fire Medallion",
    "Fire Temple Boss Key": "Fire Temple BK",
    "Forest Medallion": "Forest Medallion",
    "Forest Temple Boss Key": "Forest Temple BK",
    "Free all 9 Gorons in Fire Temple": "9 Gorons",
    "Frog's HP": "Frog's HP",
    "Ganon's Castle Boss Key": "Ganon's Castle BK",
    "Gerudo's Card": "Gerudo's Card",
    "Get Bombchu chest in Spirit Temple": "Bombchu chest in Spirit",
    "Giant's Knife": "Giant's Knife",
    "Giant's Wallet": "Giant's Wallet",
    "Golden Gauntlets": "Golden Gauntlets",
    "Golden Scale": "Golden Scale",
    "Goron Bracelet": "Goron Bracelet",
    "Goron Tunic": "Goron Tunic",
    "Goron's Ruby": "Goron's Ruby",
    "Green Gauntlets": "Green Gauntlets",
    "Green Potion": "Green Potion",
    Hookshot: "Hookshot",
    "Ice Arrows": "Ice Arrows",
    "Ice Cavern HP": "Ice Cavern HP",
    "Iron Boots": "Iron Boots",
    "Keaton Mask": "Keaton Mask",
    "Kokiri's Emerald": "Kokiri's Emerald",
    "Lens of Truth": "Lens of Truth",
    "Light Arrows": "Light Arrows",
    "Lon Lon Ranch HP": "Lon Lon HP",
    Longshot: "Longshot",
    "Lost Dog HP": "Dog HP",
    "Magic Bar": "Magic",
    "Map & Compass in Bottom of the Well": "Map & Compass in BotW",
    "Map & Compass in Deku Tree": "Map & Compass in Deku",
    "Map & Compass in Dodongo's Cavern": "Map & Compass in DC",
    "Map & Compass in Fire Temple": "Map & Compass in Fire",
    "Map & Compass in Forest Temple": "Map & Compass in Forest",
    "Map & Compass in Ice Cavern": "Map & Compass in Ice",
    "Map & Compass in Jabu-Jabu": "Map & Compass in Jabu",
    "Map & Compass in Shadow Temple": "Map & Compass in Shadow",
    "Map & Compass in Spirit Temple": "Map & Compass in Spirit",
    "Map & Compass in Water Temple": "Map & Compass in Water",
    "Megaton Hammer": "Hammer",
    Milk: "Milk",
    "Minuet of Forest": "Minuet",
    "Mirror Shield": "Mirror Shield",
    "Nayru's Love": "Nayru's Love",
    "Obtain 12 Different Heart Pieces": "12 HPs",
    "Obtain 16 Different Heart Pieces": "16 HPs",
    "Obtain 3 Different Heart Containers": "3 Heart Containers",
    "Obtain 4 Different Heart Containers": "4 Heart Containers",
    "Obtain all 5 Small Keys in Forest Temple": "5 Forest keys",
    "Obtain all 5 Small Keys in Shadow Temple": "5 Shadow keys",
    "Obtain all 8 Small Keys in Fire Temple": "8 Fire keys",
    "Open 2 Boss Key Doors": "2 boss doors",
    "Open 3 Boss Key Doors": "3 boss doors",
    "Open 3 Gold Rupee Chests": "3 Gold Rupee chests",
    "Open 5 Gold Rupee Chests": "5 Gold Rupee chests",
    "Open 50 Rupee chest in Wasteland": "50 Rupee chest in Wasteland",
    "Open 50 Rupee Chest in Wasteland": "50 Rupee chest in Wasteland",
    "Open All 6 Gold Rupee Chests": "6 Gold Rupee chests",
    "Open Forest Temple Boss Key Door": "Forest Boss door",
    "Open the Final Door of Fire Trial": "Final door in Fire Trial",
    "Open the Final Door of Forest Trial": "Final door in Forest Trial",
    "Open the Final Door of Light Trial": "Final Door in Light Trial",
    "Open the Final Door of Shadow Trial": "Final Door in Shadow Trial",
    "Open the Final Door of Spirit Trial": "Final Door in Spirit Trial",
    "Open the Final Door of Water Trial": "Final Door in Water Trial",
    "Plant 3 Magic Beans": "Plant 3 Magic Beans",
    "Plant 4 Magic Beans": "Plant 4 Magic Beans",
    "Plant 5 Magic Beans": "Plant 5 Magic Beans",
    "Plant 6 Magic Beans": "Plant 6 Magic Beans",
    "Plant 7 Magic Beans": "Plant 7 Magic Beans",
    "Plant bean in Death Mountain Crater": "Plant DMC bean",
    "Quiver (40)": "Quiver (40)",
    "Quiver (50)": "Quiver (50)",
    "Red Potion": "Red Potion",
    "Requiem of Spirit": "Requiem",
    "Ruto's Letter": "Ruto's Letter",
    "Saria's Song": "Saria's",
    "Shadow Temple Boss Key": "Shadow BK",
    "Silver Gauntlets": "Silver Gauntlets",
    "Silver Scale": "Silver Scale",
    "Skull Mask": "Skull Mask",
    "Spirit Temple Boss Key": "Spirit BK",
    "Spooky Mask": "Spooky Mask",
    "Stone of Agony": "Stone of Agony",
    "Two Fairy Spells": "2 Fairy Spells",
    "Water Medallion": "Water Medallion",
    "Water Temple Boss Key": "Water BK",
    "Win Bombchu Bowling Prize": "Bombchu Bowling",
    "Zora Tunic": "Zora Tunic",
    "Zora's Sapphire": "Zora's Sapphire",
  },
};
