export default {
  locale: "en",
  strings: {
    // Current goals
    "1 Skulltula from each Adult Dungeon":
      "1 Skulltula from each Adult Dungeon",
    "1 Skulltula from each Child Dungeon":
      "1 Skulltula from each Child Dungeon",
    "1 Unused Small Key in each Adult Dungeon":
      "1 Unused Small Key in each Adult Dungeon",
    "10 Songs": "10 Songs",
    "15 Different Skulltulas": "15 Different Skulltulas",
    "2 Boss Keys": "2 Boss Keys",
    "2 Shields": "2 Shields",
    "2 Skulltulas in Lon Lon Ranch": "2 Skulltulas in Lon Lon Ranch",
    "2 Unused Keys in Gerudo Training Grounds":
      "2 Unused Keys in Gerudo Training Grounds",
    "20 Deku Sticks": "20 Deku Sticks",
    "20 Different Skulltulas": "20 Different Skulltulas",
    "200 Rupees": "200 Rupees",
    "3 Boots": "3 Boots",
    "3 Boss Keys": "3 Boss Keys",
    "3 Compasses": "3 Compasses",
    "3 Lake Hylia Skulltulas": "3 Lake Hylia Skulltulas",
    "3 Maps": "3 Maps",
    "3 Shields": "3 Shields",
    "3 Shields & 3 Boots": "3 Shields & 3 Boots",
    "3 Shields & 3 Tunics": "3 Shields & 3 Tunics",
    "3 Skulltulas in Water Temple": "3 Skulltulas in Water Temple",
    "3 Songs": "3 Songs",
    "3 Swords & 3 Boots": "3 Swords & 3 Boots",
    "3 Swords & 3 Shields": "3 Swords & 3 Shields",
    "3 Swords & 3 Tunics": "3 Swords & 3 Tunics",
    "3 Swords, Tunics, Boots, and Shields":
      "3 Swords, Tunics, Boots, and Shields",
    "3 Tunics": "3 Tunics",
    "3 Tunics & 3 Boots": "3 Tunics & 3 Boots",
    "3 Unused Keys in Gerudo Training Grounds":
      "3 Unused Keys in Gerudo Training Grounds",
    "30 Deku Nuts": "30 Deku Nuts",
    "30 Deku Sticks": "30 Deku Sticks",
    "30 Different Skulltulas": "30 Different Skulltulas",
    "37th Heart Piece (Child Fortress)": "37th Heart Piece (Child Fortress)",
    "4 Compasses": "4 Compasses",
    "4 Maps": "4 Maps",
    "4 Skulltulas in Shadow Temple": "4 Skulltulas in Shadow Temple",
    "4 Songs": "4 Songs",
    "4 Unused Keys in Forest Temple": "4 Unused Keys in Forest Temple",
    "4 Unused Keys in Gerudo Training Grounds":
      "4 Unused Keys in Gerudo Training Grounds",
    "5 Compasses": "5 Compasses",
    "5 Hearts": "5 Hearts",
    "5 Magic Beans": "5 Magic Beans",
    "5 Maps": "5 Maps",
    "5 Unused Keys in Gerudo Training Grounds":
      "5 Unused Keys in Gerudo Training Grounds",
    "5 Zora area HPs": "5 Zora area HPs",
    "500 Rupees": "500 Rupees",
    "6 Compasses": "6 Compasses",
    "6 Different Unused Keys in Gerudo Training Grounds":
      "6 Different Unused Keys in Gerudo Training Grounds",
    "6 Hearts": "6 Hearts",
    "6 Magic Beans": "6 Magic Beans",
    "6 Maps": "6 Maps",
    "6 Songs": "6 Songs",
    "6 Unused Keys in Gerudo Training Grounds":
      "6 Unused Keys in Gerudo Training Grounds",
    "7 Compasses": "7 Compasses",
    "7 Different Bottled Contents": "7 Different Bottled Contents",
    "7 Different Unused Keys in Gerudo Training Grounds":
      "7 Different Unused Keys in Gerudo Training Grounds",
    "7 Hearts (no duping)": "7 Hearts (no duping)",
    "7 Magic Beans": "7 Magic Beans",
    "7 Maps": "7 Maps",
    "7 Songs": "7 Songs",
    "8 Different Unused Keys in Gerudo Training Grounds":
      "8 Different Unused Keys in Gerudo Training Grounds",
    "8 Hearts (no duping)": "8 Hearts (no duping)",
    "8 Magic Beans": "8 Magic Beans",
    "8 Songs": "8 Songs",
    "9 Hearts (no duping)": "9 Hearts (no duping)",
    "9 Magic Beans": "9 Magic Beans",
    "9 Songs": "9 Songs",
    "99 Rupees": "99 Rupees",
    "Adult's Wallet": "Adult's Wallet",
    "All 3 Child Lake Hylia Skulltulas": "All 3 Child Lake Hylia Skulltulas",
    "All 3 Elemental Arrows": "All 3 Elemental Arrows",
    "All 3 Kokiri Forest area Skulltulas":
      "All 3 Kokiri Forest area Skulltulas",
    "All 3 Skulltulas in Bottom of the Well":
      "All 3 Skulltulas in Bottom of the Well",
    "All 3 Skulltulas in Ice Cavern": "All 3 Skulltulas in Ice Cavern",
    "All 4 Adult Zora's Domain area Skulltulas":
      "All 4 Adult Zora's Domain area Skulltulas",
    "All 4 Child Zora's Domain area Skulltulas":
      "All 4 Child Zora's Domain area Skulltulas",
    "All 4 Gerudo Valley area Skulltulas":
      "All 4 Gerudo Valley area Skulltulas",
    "All 4 Lon Lon Ranch area Skulltulas":
      "All 4 Lon Lon Ranch area Skulltulas",
    "All 4 Lost Woods area Skulltulas": "All 4 Lost Woods area Skulltulas",
    "All 4 Market area Skulltulas": "All 4 Market area Skulltulas",
    "All 4 Skulltulas in Deku Tree": "All 4 Skulltulas in Deku Tree",
    "All 4 Skulltulas in Jabu-Jabu": "All 4 Skulltulas in Jabu-Jabu",
    "All 4 Wasteland/ Colossus area Skulltulas":
      "All 4 Wasteland/ Colossus area Skulltulas",
    "All 5 Child Death Mountain area Skulltulas":
      "All 5 Child Death Mountain area Skulltulas",
    "All 5 Lake Hylia Skulltulas": "All 5 Lake Hylia Skulltulas",
    "All 5 Skulltulas in Dodongo's Cavern":
      "All 5 Skulltulas in Dodongo's Cavern",
    "All 5 Skulltulas in Fire Temple": "All 5 Skulltulas in Fire Temple",
    "All 5 Skulltulas in Forest Temple": "All 5 Skulltulas in Forest Temple",
    "All 5 Skulltulas in Shadow Temple": "All 5 Skulltulas in Shadow Temple",
    "All 5 Skulltulas in Spirit Temple": "All 5 Skulltulas in Spirit Temple",
    "All 5 Skulltulas in Water Temple": "All 5 Skulltulas in Water Temple",
    "All 7 Child Kakariko area Skulltulas":
      "All 7 Child Kakariko area Skulltulas",
    "All 8 Death Mountain area Skulltulas":
      "All 8 Death Mountain area Skulltulas",
    "All 8 Kakariko area Skulltulas": "All 8 Kakariko area Skulltulas",
    "All 8 Zora's Domain area Skulltulas":
      "All 8 Zora's Domain area Skulltulas",
    "Beat Dodongo's Cavern": "Beat Dodongo's Cavern",
    "Beat Jabu-Jabu's Belly": "Beat Jabu-Jabu's Belly",
    "Beat the Deku Tree": "Beat the Deku Tree",
    "Beat the Fire Temple": "Beat the Fire Temple",
    "Beat the Forest Temple": "Beat the Forest Temple",
    "Beat the Shadow Temple": "Beat the Shadow Temple",
    "Beat the Spirit Temple": "Beat the Spirit Temple",
    "Beat the Water Temple": "Beat the Water Temple",
    "Biggoron's Sword": "Biggoron's Sword",
    "Blue Fire": "Blue Fire",
    "Blue Gauntlets": "Blue Gauntlets",
    "Blue Potion": "Blue Potion",
    "Bolero of Fire": "Bolero of Fire",
    "Bomb Bag (30)": "Bomb Bag (30)",
    Boomerang: "Boomerang",
    "Both Child Gerudo Valley area Skulltulas":
      "Both Child Gerudo Valley area Skulltulas",
    "Both Child Kokiri Forest area Skulltulas":
      "Both Child Kokiri Forest area Skulltulas",
    "Both Child Lost Woods area Skulltulas":
      "Both Child Lost Woods area Skulltulas",
    "Both Child Wasteland/ Colossus area Skulltulas":
      "Both Child Wasteland/ Colossus area Skulltulas",
    "Both Gerudo Valley HPs": "Both Gerudo Valley HPs",
    "Both Gerudo's Fortress area Skulltulas":
      "Both Gerudo's Fortress area Skulltulas",
    "Both HPs in Death Mountain Crater": "Both HPs in Death Mountain Crater",
    "Both HPs in Lost Woods": "Both HPs in Lost Woods",
    "Both Hyrule Field area Skulltulas": "Both Hyrule Field area Skulltulas",
    "Both Rusty Switches in Spirit Temple":
      "Both Rusty Switches in Spirit Temple",
    "Bottled Fairy": "Bottled Fairy",
    "Bottled Poe": "Bottled Poe",
    "Bronze Gauntlets": "Bronze Gauntlets",
    "Bullet Bag (40)": "Bullet Bag (40)",
    "Bullet Bag (50)": "Bullet Bag (50)",
    "Clear 10 Silver Rupee Rooms": "Clear 10 Silver Rupee Rooms",
    "Clear 4 Silver Rupee Rooms": "Clear 4 Silver Rupee Rooms",
    "Clear 8 Silver Rupee Rooms": "Clear 8 Silver Rupee Rooms",
    "Cow in House": "Cow in House",
    "Defeat 10 Different Stalfos": "Defeat 10 Different Stalfos",
    "Defeat 4 Different Iron Knuckles": "Defeat 4 Different Iron Knuckles",
    "Defeat 5 Different Stalfos": "Defeat 5 Different Stalfos",
    "Defeat a Skull Kid": "Defeat a Skull Kid",
    "Defeat a White Wolfos": "Defeat a White Wolfos",
    "Defeat all Lizalfos in Dodongo's Cavern":
      "Defeat all Lizalfos in Dodongo's Cavern",
    "Defeat Amy (Green Poe)": "Defeat Amy (Green Poe)",
    "Defeat Barinade": "Defeat Barinade",
    "Defeat Big Octo": "Defeat Big Octo",
    "Defeat Bongo-Bongo": "Defeat Bongo-Bongo",
    "Defeat both Flare Dancers": "Defeat both Flare Dancers",
    "Defeat Dark Link": "Defeat Dark Link",
    "Defeat King Dodongo": "Defeat King Dodongo",
    "Defeat Meg (Purple Poe)": "Defeat Meg (Purple Poe)",
    "Defeat Morpha": "Defeat Morpha",
    "Defeat Nabooru-Knuckle": "Defeat Nabooru-Knuckle",
    "Defeat Phantom Ganon": "Defeat Phantom Ganon",
    "Defeat Queen Gohma": "Defeat Queen Gohma",
    "Defeat Twinrova": "Defeat Twinrova",
    "Defeat Volvagia": "Defeat Volvagia",
    "Desert Colossus HP": "Desert Colossus HP",
    "Din's Fire": "Din's Fire",
    "Double Defense": "Double Defense",
    "Double Magic": "Double Magic",
    "Epona's Song": "Epona's Song",
    "Exactly 20 Deku Sticks": "Exactly 20 Deku Sticks",
    "Exactly 30 Deku Sticks": "Exactly 30 Deku Sticks",
    "Fairy Bow": "Fairy Bow",
    "Fairy Ocarina": "Fairy Ocarina",
    "Fairy Slingshot": "Fairy Slingshot",
    "Farore's Wind": "Farore's Wind",
    "Fill 20 Item Inventory Slots": "Fill 20 Item Inventory Slots",
    "Fill all 4 Bottle Slots": "Fill all 4 Bottle Slots",
    "Fire Arrows": "Fire Arrows",
    "Fire Medallion": "Fire Medallion",
    "Fire Temple Boss Key": "Fire Temple Boss Key",
    "Forest Medallion": "Forest Medallion",
    "Forest Temple Boss Key": "Forest Temple Boss Key",
    "Free all 9 Gorons in Fire Temple": "Free all 9 Gorons in Fire Temple",
    "Frog's HP": "Frog's HP",
    "Ganon's Castle Boss Key": "Ganon's Castle Boss Key",
    "Gerudo's Card": "Gerudo's Card",
    "Get Bombchu chest in Spirit Temple": "Get Bombchu chest in Spirit Temple",
    "Giant's Knife": "Giant's Knife",
    "Giant's Wallet": "Giant's Wallet",
    "Golden Gauntlets": "Golden Gauntlets",
    "Golden Scale": "Golden Scale",
    "Goron Bracelet": "Goron Bracelet",
    "Goron Tunic": "Goron Tunic",
    "Goron's Ruby": "Goron's Ruby",
    "Green Gauntlets": "Green Gauntlets",
    "Green Potion": "Green Potion",
    Hookshot: "Hookshot",
    "Ice Arrows": "Ice Arrows",
    "Ice Cavern HP": "Ice Cavern HP",
    "Iron Boots": "Iron Boots",
    "Keaton Mask": "Keaton Mask",
    "Kokiri's Emerald": "Kokiri's Emerald",
    "Lens of Truth": "Lens of Truth",
    "Light Arrows": "Light Arrows",
    "Lon Lon Ranch HP": "Lon Lon Ranch HP",
    Longshot: "Longshot",
    "Lost Dog HP": "Lost Dog HP",
    "Magic Bar": "Magic Bar",
    "Map & Compass in Bottom of the Well":
      "Map & Compass in Bottom of the Well",
    "Map & Compass in Deku Tree": "Map & Compass in Deku Tree",
    "Map & Compass in Dodongo's Cavern": "Map & Compass in Dodongo's Cavern",
    "Map & Compass in Fire Temple": "Map & Compass in Fire Temple",
    "Map & Compass in Forest Temple": "Map & Compass in Forest Temple",
    "Map & Compass in Ice Cavern": "Map & Compass in Ice Cavern",
    "Map & Compass in Jabu-Jabu": "Map & Compass in Jabu-Jabu",
    "Map & Compass in Shadow Temple": "Map & Compass in Shadow Temple",
    "Map & Compass in Spirit Temple": "Map & Compass in Spirit Temple",
    "Map & Compass in Water Temple": "Map & Compass in Water Temple",
    "Megaton Hammer": "Megaton Hammer",
    Milk: "Milk",
    "Minuet of Forest": "Minuet of Forest",
    "Mirror Shield": "Mirror Shield",
    "Nayru's Love": "Nayru's Love",
    "Obtain 12 Different Heart Pieces": "Obtain 12 Different Heart Pieces",
    "Obtain 16 Different Heart Pieces": "Obtain 16 Different Heart Pieces",
    "Obtain 3 Different Heart Containers":
      "Obtain 3 Different Heart Containers",
    "Obtain 4 Different Heart Containers":
      "Obtain 4 Different Heart Containers",
    "Obtain all 5 Small Keys in Forest Temple":
      "Obtain all 5 Small Keys in Forest Temple",
    "Obtain all 5 Small Keys in Shadow Temple":
      "Obtain all 5 Small Keys in Shadow Temple",
    "Obtain all 8 Small Keys in Fire Temple":
      "Obtain all 8 Small Keys in Fire Temple",
    "Open 2 Boss Key Doors": "Open 2 Boss Key Doors",
    "Open 3 Boss Key Doors": "Open 3 Boss Key Doors",
    "Open 3 Gold Rupee Chests": "Open 3 Gold Rupee Chests",
    "Open 5 Gold Rupee Chests": "Open 5 Gold Rupee Chests",
    "Open 50 Rupee chest in Wasteland": "Open 50 Rupee chest in Wasteland",
    "Open 50 Rupee Chest in Wasteland": "Open 50 Rupee Chest in Wasteland",
    "Open All 6 Gold Rupee Chests": "Open All 6 Gold Rupee Chests",
    "Open Forest Temple Boss Key Door": "Open Forest Temple Boss Key Door",
    "Open the Final Door of Fire Trial": "Open the Final Door of Fire Trial",
    "Open the Final Door of Forest Trial":
      "Open the Final Door of Forest Trial",
    "Open the Final Door of Light Trial": "Open the Final Door of Light Trial",
    "Open the Final Door of Shadow Trial":
      "Open the Final Door of Shadow Trial",
    "Open the Final Door of Spirit Trial":
      "Open the Final Door of Spirit Trial",
    "Open the Final Door of Water Trial": "Open the Final Door of Water Trial",
    "Plant 3 Magic Beans": "Plant 3 Magic Beans",
    "Plant 4 Magic Beans": "Plant 4 Magic Beans",
    "Plant 5 Magic Beans": "Plant 5 Magic Beans",
    "Plant 6 Magic Beans": "Plant 6 Magic Beans",
    "Plant 7 Magic Beans": "Plant 7 Magic Beans",
    "Plant bean in Death Mountain Crater":
      "Plant bean in Death Mountain Crater",
    "Quiver (40)": "Quiver (40)",
    "Quiver (50)": "Quiver (50)",
    "Red Potion": "Red Potion",
    "Requiem of Spirit": "Requiem of Spirit",
    "Ruto's Letter": "Ruto's Letter",
    "Saria's Song": "Saria's Song",
    "Shadow Temple Boss Key": "Shadow Temple Boss Key",
    "Silver Gauntlets": "Silver Gauntlets",
    "Silver Scale": "Silver Scale",
    "Skull Mask": "Skull Mask",
    "Spirit Temple Boss Key": "Spirit Temple Boss Key",
    "Spooky Mask": "Spooky Mask",
    "Stone of Agony": "Stone of Agony",
    "Two Fairy Spells": "Two Fairy Spells",
    "Water Medallion": "Water Medallion",
    "Water Temple Boss Key": "Water Temple Boss Key",
    "Win Bombchu Bowling Prize": "Win Bombchu Bowling Prize",
    "Zora Tunic": "Zora Tunic",
    "Zora's Sapphire": "Zora's Sapphire",

    // Legacy goals
    "2 unused keys in Gerudo Training Grounds":
      "2 unused keys in Gerudo Training Grounds",
    "3 unused keys in Gerudo Training Grounds":
      "3 unused keys in Gerudo Training Grounds",
    "37th heart piece (Child Fortress)": "37th heart piece (Child Fortress)",
    "4 unused keys in Gerudo Training Grounds":
      "4 unused keys in Gerudo Training Grounds",
    "5 unused keys in Gerudo Training Grounds":
      "5 unused keys in Gerudo Training Grounds",
    "6 unused keys in Gerudo Training Grounds":
      "6 unused keys in Gerudo Training Grounds",
    "Both heart pieces in Death Mountain Crater":
      "Both heart pieces in Death Mountain Crater",
    "Both heart pieces in Lost Woods": "Both heart pieces in Lost Woods",
    "Ocarina of Time": "Ocarina of Time",
    "Open 3 gold rupee chests": "Open 3 gold rupee chests",
    "All 4 Adult Skulltulas in Zora's Domain Area":
      "All 4 Adult Skulltulas in Zora's Domain Area",
    "All 4 Child Skulltulas in Zora's Domain Area":
      "All 4 Child Skulltulas in Zora's Domain Area",
    "Defeat Meg (purple Poe)": "Defeat Meg (purple Poe)",
    "7 Hearts": "7 Hearts",
    "All 4 Lon-Lon Ranch area Skulltulas":
      "All 4 Lon-Lon Ranch area Skulltulas",
    "Get to the end of Fire Trial": "Get to the end of Fire Trial",
    "Get to the end of Forest Trial": "Get to the end of Forest Trial",
    "Get to the end of Light Trial": "Get to the end of Light Trial",
    "Get to the end of Shadow Trial": "Get to the end of Shadow Trial",
    "Get to the end of Spirit Trial": "Get to the end of Spirit Trial",
    "Get to the end of Water Trial": "Get to the end of Water Trial",
    "2 Lon Lon Ranch Area Skulltulas": "2 Lon Lon Ranch Area Skulltulas",
    "5 Zora Area HPs": "5 Zora Area HPs",
    "8 Hearts (No Duping)": "8 Hearts (No Duping)",
    "9 Hearts (No Duping)": "9 Hearts (No Duping)",
    "All 3 Kokiri Forest Area Skulltulas":
      "All 3 Kokiri Forest Area Skulltulas",
    "All 4 Gerudo Valley Area Skulltulas":
      "All 4 Gerudo Valley Area Skulltulas",
    "All 4 Lon Lon Ranch Area Skulltulas":
      "All 4 Lon Lon Ranch Area Skulltulas",
    "All 4 Lost Woods Area Skulltulas": "All 4 Lost Woods Area Skulltulas",
    "All 4 Market Area Skulltulas": "All 4 Market Area Skulltulas",
    "All 4 Wasteland/ Colossus Area Skulltulas":
      "All 4 Wasteland/ Colossus Area Skulltulas",
    "All 8 Death Mountain Area Skulltulas":
      "All 8 Death Mountain Area Skulltulas",
    "All 8 Kakariko Area Skulltulas": "All 8 Kakariko Area Skulltulas",
    "All 8 Zora's Domain Area Skulltulas":
      "All 8 Zora's Domain Area Skulltulas",
    "Both Gerudo's Fortress Area Skulltulas":
      "Both Gerudo's Fortress Area Skulltulas",
    "Both Hyrule Field Area Skulltulas": "Both Hyrule Field Area Skulltulas",
    "Plant Bean in Death Mountain Crater":
      "Plant Bean in Death Mountain Crater",
    "All 4 Adult Skulltulas in Zora's Domain":
      "All 4 Adult Skulltulas in Zora's Domain",
    "All 4 Child Skulltulas in Zora's Domain":
      "All 4 Child Skulltulas in Zora's Domain",
    "8 Hearts": "8 Hearts",
    "9 Hearts": "9 Hearts",
    "1 unused small key in each Adult Dungeon":
      "1 unused small key in each Adult Dungeon",
    "3 songs": "3 songs",
    "7 different unused keys in Gerudo Training Grounds":
      "7 different unused keys in Gerudo Training Grounds",
    "8 different unused keys in Gerudo Training Grounds":
      "8 different unused keys in Gerudo Training Grounds",
    "Free all 9 gorons in Fire Temple": "Free all 9 gorons in Fire Temple",
    "Frog's Heart Piece": "Frog's Heart Piece",
    "Ice Cavern Heart Piece": "Ice Cavern Heart Piece",
    "Zora's Saphire": "Zora's Saphire",
    "15 Unique Skulltulas": "15 Unique Skulltulas",
    "9 different unused keys in Gerudo Training Grounds":
      "9 different unused keys in Gerudo Training Grounds",
    "At Least 1 Skulltula from each Adult Dungeon":
      "At Least 1 Skulltula from each Adult Dungeon",
    "At Least 1 Skulltula from each Child Dungeon":
      "At Least 1 Skulltula from each Child Dungeon",
    "At least 1 unused key in each Adult Dungeon":
      "At least 1 unused key in each Adult Dungeon",
    "At least 10 songs": "At least 10 songs",
    "At Least 3 Lake Hylia Skulltulas": "At Least 3 Lake Hylia Skulltulas",
    "At least 3 Skulltulas in Water Temple":
      "At least 3 Skulltulas in Water Temple",
    "At least 3 songs": "At least 3 songs",
    "At least 30 Deku Nuts": "At least 30 Deku Nuts",
    "At least 4 Skulltulas in Shadow Temple":
      "At least 4 Skulltulas in Shadow Temple",
    "At least 4 songs": "At least 4 songs",
    "At Least 5 Magic Beans": "At Least 5 Magic Beans",
    "At Least 5 Zora Area HPs": "At Least 5 Zora Area HPs",
    "At least 6 songs": "At least 6 songs",
    "At least 7 Magic Beans": "At least 7 Magic Beans",
    "At Least 7 Songs": "At Least 7 Songs",
    "At least 8 songs": "At least 8 songs",
    "At least 9 Magic Beans": "At least 9 Magic Beans",
    "At least 9 songs": "At least 9 songs",
    "Defeat 4 Iron Knuckles": "Defeat 4 Iron Knuckles",
    "Fire Arrow": "Fire Arrow",
    "Open all 5 Small Key chests in Forest Temple":
      "Open all 5 Small Key chests in Forest Temple",
    "Open all 5 Small Key chests in Shadow Temple":
      "Open all 5 Small Key chests in Shadow Temple",
    "Open all 8 Small Key chests in Fire Temple":
      "Open all 8 Small Key chests in Fire Temple",
    "Bombchu Bowling Heart Piece": "Bombchu Bowling Heart Piece",
    "Get to the end of the Forest Trial": "Get to the end of the Forest Trial",
    "Bottled Big Poe": "Bottled Big Poe",
    "8 unused keys in Gerudo Training Grounds":
      "8 unused keys in Gerudo Training Grounds",
    "At least 5 songs": "At least 5 songs",
    "Black Gauntlets": "Black Gauntlets",
    "Bottled Fish": "Bottled Fish",
    "Bunny Hood": "Bunny Hood",
    "Prelude of Light": "Prelude of Light",
    "Serenade of Water": "Serenade of Water",
    "Treasure Chest Game Heart Piece": "Treasure Chest Game Heart Piece",
    "7 unused keys in Gerudo Training Grounds":
      "7 unused keys in Gerudo Training Grounds",
    "At least 4 Skulltulas in Water Temple":
      "At least 4 Skulltulas in Water Temple",
    "10 Hearts": "10 Hearts",
    "4 Boss Keys": "4 Boss Keys",
    "9 unused keys in Gerudo Training Grounds":
      "9 unused keys in Gerudo Training Grounds",
    "At least 7 songs": "At least 7 songs",
    "Biggoron窶冱 Sword": "Biggoron窶冱 Sword",
    "Bomb Bag (40)": "Bomb Bag (40)",
    "Broken Goron's Sword": "Broken Goron's Sword",
    "Claim Check": "Claim Check",
    Cojiro: "Cojiro",
    "Defeat Ganon": "Defeat Ganon",
    "Odd Potion": "Odd Potion",
    "Poacher's Saw": "Poacher's Saw",
    "Pocket Cucco": "Pocket Cucco",
    Prescription: "Prescription",
    "3 Swords": "3 Swords",
    "Defeat both Dead-Hands": "Defeat both Dead-Hands",
    "Never obtain Bombchus": "Never obtain Bombchus",
    "Never obtain Hookshot": "Never obtain Hookshot",
    "Never save": "Never save",
    "Nocturne of Shadow": "Nocturne of Shadow",
    "Obtain the Bombchu chest in Ganon's Castle":
      "Obtain the Bombchu chest in Ganon's Castle",
    "50 Bombchus": "50 Bombchus",
    "At least 20 Deku Sticks": "At least 20 Deku Sticks",
    "37th heart piece (Fortress)": "37th heart piece (Fortress)",
    "All Death Mountain area Skulltulas": "All Death Mountain area Skulltulas",
    "All Gerudo Fortress area Skulltulas":
      "All Gerudo Fortress area Skulltulas",
    "All Gerudo Valley area Skulltulas": "All Gerudo Valley area Skulltulas",
    "All Hyrule Field area Skulltulas": "All Hyrule Field area Skulltulas",
    "All Kakariko area Skulltulas": "All Kakariko area Skulltulas",
    "All Kokiri Forest area Skulltulas": "All Kokiri Forest area Skulltulas",
    "All Lake Hylia Skulltulas": "All Lake Hylia Skulltulas",
    "All Lon-Lon Ranch area Skulltulas": "All Lon-Lon Ranch area Skulltulas",
    "All Lost Woods area Skulltulas": "All Lost Woods area Skulltulas",
    "All Market area Skulltulas": "All Market area Skulltulas",
    "All Skulltulas in Bottom of the Well":
      "All Skulltulas in Bottom of the Well",
    "All Skulltulas in Deku Tree": "All Skulltulas in Deku Tree",
    "All Skulltulas in Dodongo's Cavern": "All Skulltulas in Dodongo's Cavern",
    "All Skulltulas in Fire Temple": "All Skulltulas in Fire Temple",
    "All Skulltulas in Forest Temple": "All Skulltulas in Forest Temple",
    "All Skulltulas in Ice Cavern": "All Skulltulas in Ice Cavern",
    "All Skulltulas in Jabu-Jabu": "All Skulltulas in Jabu-Jabu",
    "All Skulltulas in Shadow Temple": "All Skulltulas in Shadow Temple",
    "All Skulltulas in Spirit Temple": "All Skulltulas in Spirit Temple",
    "All Skulltulas in Water Temple": "All Skulltulas in Water Temple",
    "All Zora's Domain area Skulltulas": "All Zora's Domain area Skulltulas",

    // UI
    " / ": " / ",
    " - ": " - ",
    ": Boss keys for child dungeons obtained through RBA count":
      ": Boss keys for child dungeons obtained through RBA count",
    ": Ice Cavern and Jabu-Jabu do not count":
      ": Ice Cavern and Jabu-Jabu do not count",
    ": Item must display visually in inventory to count":
      ": Item must display visually in inventory to count",
    ": Only dungeons with blue warps are required":
      ": Only dungeons with blue warps are required",
    ": Only one of the frog's HPs is required":
      ": Only one of the frog's HPs is required",
    ": Planting multiple beans in the same location (e.g. by duping soft soil patches) is not allowed":
      ": Planting multiple beans in the same location (e.g. by duping soft soil patches) is not allowed",
    ": Scarecrow's Song does not count": ": Scarecrow's Song does not count",
    ": Using RBA to write Heart Pieces into the inventory does not count as duping and is allowed":
      ": Using RBA to write Heart Pieces into the inventory does not count as duping and is allowed",
    About: "About",
    "All required items must be present in the inventory in order to finish. For example, for the goal <i>Blue Potion</i>, you must not drink it":
      "All required items must be present in the inventory in order to finish. For example, for the goal <i>Blue Potion</i>, you must not drink it",
    "Animation time": "Animation time",
    "Arbitrary Code Execution (ACE)": "Arbitrary Code Execution (ACE)",
    "BL-TR": "BL-TR",
    BOARD: "BOARD",
    "Background color": "Background color",
    "Banned Tricks": "Banned Tricks",
    "Beat Dungeon: When you step in the blue warp and lose control or skip the cutscene":
      "Beat Dungeon: When you step in the blue warp and lose control or skip the cutscene",
    "Defeat an Enemy: When you strike the last blow and the death animation completes. If defeating the enemy is permanent, when the associated cutscene begins":
      "Defeat an Enemy: When you strike the last blow and the death animation completes. If defeating the enemy is permanent, when the associated cutscene begins",
    "Defeat a Boss: When you strike the last blow and the death cutscene begins":
        "Defeat a Boss: When you strike the last blow and the death cutscene begins",
    "Bingo Popout": "Bingo Popout",
    "Blackout card": "Blackout card",
    "Border color": "Border color",
    "Border width": "Border width",
    COL1: "COL1",
    COL2: "COL2",
    COL3: "COL3",
    COL4: "COL4",
    COL5: "COL5",
    counter: "counter",
    "Cell height": "Cell height",
    "Cell width": "Cell width",
    "Counter icon size": "Counter icon size",
    "Counter text size": "Counter text size",
    Credits: "Credits",
    "Emphasis text color": "Emphasis text color",
    "Exodus, tob3000, Runnerguy2489, Tasselhoff, juwk, shaggy, triforce3250, 2DollarGargoyle, Link11, EggMeister":
      "Exodus, tob3000, Runnerguy2489, Tasselhoff, juwk, shaggy, triforce3250, 2DollarGargoyle, Link11, EggMeister",
    "Export (general)": "Export (general)",
    "Export (tracker)": "Export (tracker)",
    "Failed to generate board": "Failed to generate board",
    "Filename:": "Filename:",
    Font: "Font",
    Generator: "Generator",
    "Goal List": "Goal List",
    "Goal Clarifications": "Goal Clarifications",
    "Gombill, Runnerguy2489, Zamiel, Exodus, SnipinG117, Moose1137, Runnerguy2489, tob3000, Tasselhoff, juwk":
      "Gombill, Runnerguy2489, Zamiel, Exodus, SnipinG117, Moose1137, Runnerguy2489, tob3000, Tasselhoff, juwk",
    "Green background color": "Green background color",
    "Header height": "Header height",
    "Header width": "Header width",
    "Header text color": "Header text color",
    "Hover background color": "Hover background color",
    "Hover border color": "Hover border color",
    "Hover green background color": "Hover green background color",
    "Hover red background color": "Hover red background color",
    "Hover text color": "Hover text color",
    "If Wrong Warping, any items or goals associated with the wrong warp are obtained upon completion of the Wrong Warp":
      "If Wrong Warping, any items or goals associated with the wrong warp are obtained upon completion of the Wrong Warp",
    "Import (general)": "Import (general)",
    "Import (tracker)": "Import (tracker)",
    "Item: When you are holding it above your head":
      "Item: When you are holding it above your head",
    "Jumpslash Quick Putaway (QPA)": "Jumpslash Quick Putaway (QPA)",
    Language: "Language",
    "Line height": "Line height",
    "Max token size": "Max token size",
    "Mode:": "Mode:",
    "Normal card": "Normal card",
    none: "none",
    "Numbers are minimums. Collecting more than enough is allowed unless otherwise stated":
      "Numbers are minimums. Collecting more than enough is allowed unless otherwise stated",
    "Obtaining the Eyeball Frog without presenting the Prescription (Hold R)":
      "Obtaining the Eyeball Frog without presenting the Prescription (Hold R)",
    "Ocarina of Time Bingo": "Ocarina of Time Bingo",
    "Originally written and designed by Narcissa. Improved by Giuocob. v9 redesign by Saltor. Frequency Balancing by prettybigjoe.":
      "Originally written and designed by Narcissa. Improved by Giuocob. v9 redesign by Saltor. Frequency Balancing by prettybigjoe.",
    "Other Rules": "Other Rules",
    "Other versions": "Other versions",
    Padding: "Padding",
    "Page background color": "Page background color",
    ROW1: "ROW1",
    ROW2: "ROW2",
    ROW3: "ROW3",
    ROW4: "ROW4",
    ROW5: "ROW5",
    "Red background color": "Red background color",
    Reset: "Reset",
    Rules: "Rules",
    Save: "Save",
    "Seed:": "Seed:",
    Settings: "Settings",
    "Shadow opacity": "Shadow opacity",
    "Short card": "Short card",
    "Show counter denominator": "Show counter denominator",
    "Show in blackout mode": "Show in blackout mode",
    "Show in normal/short mode": "Show in normal/short mode",
    "Show random filename": "Show random filename",
    "Show tracker": "Show tracker",
    'Song: When the dialog box that says "You have learned the…" completes':
      'Song: When the dialog box that says "You have learned the…" completes',
    "Stale Reference Manipulation (SRM)": "Stale Reference Manipulation (SRM)",
    tokens: "tokens",
    "TL-BR": "TL-BR",
    "Text color": "Text color",
    "Text size": "Text size",
    "The goals are balanced around playing on the Japanese version of Ocarina of Time":
      "The goals are balanced around playing on the Japanese version of Ocarina of Time",
    "This is a <i>Bingo</i> board for Ocarina of Time races":
      "This is a <i>Bingo</i> board for Ocarina of Time races",
    "To win, you must complete 5 of the tasks in a row horizontally, vertically, or diagonally":
      "To win, you must complete 5 of the tasks in a row horizontally, vertically, or diagonally",
    "Unlike in most speedrunning categories, the intro cutscene should not be skipped. This gives players a few minutes to plan":
      "Unlike in most speedrunning categories, the intro cutscene should not be skipped. This gives players a few minutes to plan",
    "Using Bombchus out of bounds": "Using Bombchus out of bounds",
    "Using Deku Stick as adult": "Using Deku Stick as adult",
    "When an item may be marked as completed:":
      "When an item may be marked as completed:",
    "Version:": "Version:",
    v9: "v9",
    v10: "v10",
    X: "X",
    "You can click on the squares to turn them green and red. This may help you organize your route planning":
      "You can click on the squares to turn them green and red. This may help you organize your route planning",
    "The page you are looking for does not exist":
      "The page you are looking for does not exist",
    "Show All Versions": "Show All Versions",
  },
};
