export default {
  locale: "ja",
  strings: {
    // Current goals
    "1 Skulltula from each Adult Dungeon":
      "全ての大人ダンジョンからスタルチュラ最低１匹ずつ",
    "1 Skulltula from each Child Dungeon":
      "全ての子供ダンジョンからスタルチュラ最低１匹ずつ",
    "1 Unused Small Key in each Adult Dungeon":
      "全ての大人のダンジョンから未使用の鍵最低１つずつ",
    "10 Songs": "歌１&#8288;０つ以上",
    "15 Different Skulltulas": "スタルチュラのしるし１&#8288;５個（増殖禁止）",
    "2 Boss Keys": "ボス部屋の鍵２つ",
    "2 Shields": "盾２種",
    "2 Skulltulas in Lon Lon Ranch":
      "ロンロン牧場エリアの黄金のスタルチュラ２匹",
    "2 Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ２つ",
    "20 Deku Sticks": "デクの棒２&#8288;０本",
    "20 Different Skulltulas": "スタルチュラのしるし３&#8288;０個（増殖禁止）",
    "200 Rupees": "２&#8288;００ルピー",
    "3 Boots": "靴３種",
    "3 Boss Keys": "ボス部屋の鍵３つ",
    "3 Compasses": "コンパス３つ",
    "3 Lake Hylia Skulltulas": "ハイリア湖畔エリアの黄金のスタルチュラ３匹以上",
    "3 Maps": "マップ３つ",
    "3 Shields": "盾３種",
    "3 Shields & 3 Boots": "盾３種、靴３種",
    "3 Shields & 3 Tunics": "盾３種、服３種",
    "3 Skulltulas in Water Temple": "水の神殿の黄金のスタルチュラ３匹以上",
    "3 Songs": "歌３つ以上",
    "3 Swords & 3 Boots": "剣３種、靴３種",
    "3 Swords & 3 Shields": "剣３種、盾３種",
    "3 Swords & 3 Tunics": "剣３種、服３種",
    "3 Swords, Tunics, Boots, and Shields": "剣３種、盾３種、服３種、靴３種",
    "3 Tunics": "服３種",
    "3 Tunics & 3 Boots": "服３種、靴３種",
    "3 Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵３つ",
    "30 Deku Nuts": "デクの実３&#8288;０個以上",
    "30 Deku Sticks": "デクの棒３&#8288;０本",
    "30 Different Skulltulas": "スタルチュラのしるし３&#8288;０個（増殖禁止）",
    "37th Heart Piece (Child Fortress)":
      "３&#8288;７番目のハートのかけら（子供のゲルドの砦）",
    "4 Bottles of Milk": "ロンロン牛乳4つ",
    "4 Compasses": "コンパス４つ",
    "4 Maps": "マップ４つ",
    "4 Skulltulas in Shadow Temple": "闇の神殿の黄金のスタルチュラ４匹以上",
    "4 Songs": "歌４つ以上",
    "4 Unused Keys in Forest Temple": "森の神殿の未使用の小さな鍵４つ",
    "4 Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵４つ",
    "5 Compasses": "コンパス５つ",
    "5 Hearts": "ハート５つ",
    "5 Magic Beans": "魔法のマメ５つ以上",
    "5 Maps": "マップ５つ",
    "5 Top Row Songs": "上段の歌5つ以上",
    "5 Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵５つ",
    "5 Zora area HPs": "ゾーラエリアのハートのかけら５つ以上",
    "500 Rupees": "５&#8288;０&#8288;０ルピー",
    "6 Compasses": "コンパス６つ",
    "6 Different Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵６つ",
    "6 Hearts": "ハート６つ",
    "6 Magic Beans": "魔法のマメ６つ以上",
    "6 Maps": "マップ６つ",
    "6 Songs": "歌６つ以上",
    "6 Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ６つ",
    "7 Compasses": "コンパス７つ",
    "7 Different Bottled Contents": "ビンに詰めたアイテム７種類",
    "7 Different Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵７つ（増殖禁止）",
    "7 Hearts (no duping)": "ハート７つ",
    "7 Magic Beans": "魔法のマメ７つ以上",
    "7 Maps": "マップ７つ",
    "7 Songs": "歌７つ以上",
    "8 Different Unused Keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵８つ（増殖禁止）",
    "8 Hearts (no duping)": "ハート８つ（複製禁止）",
    "8 Magic Beans": "魔法のマメ８つ以上",
    "8 Songs": "歌８つ以上",
    "9 Hearts (no duping)": "ハート９つ（複製禁止）",
    "9 Magic Beans": "魔法のマメ９つ以上",
    "9 Songs": "歌９つ以上",
    "99 Rupees": "９&#8288;９ルピー",
    "Adult's Wallet": "大人のサイフ",
    "All 3 Child Lake Hylia Skulltulas":
      "ハイリア湖畔エリアの黄金のスタルチュラ３匹以上",
    "All 3 Elemental Arrows": "魔法矢３つ",
    "All 3 Kokiri Forest area Skulltulas":
      "コキリの森エリアの黄金のスタルチュラ３匹",
    "All 3 Skulltulas in Bottom of the Well":
      "井戸の底の黄金のスタルチュラ３匹",
    "All 3 Skulltulas in Ice Cavern": "氷の洞窟の黄金のスタルチュラ３匹",
    "All 4 Adult Zora's Domain area Skulltulas":
      "大人時代のゾーラの里エリアの黄金のスタルチュラ４匹",
    "All 4 Child Zora's Domain area Skulltulas":
      "子供時代のゾーラの里エリアの黄金のスタルチュラ４匹",
    "All 4 Gerudo Valley area Skulltulas":
      "ゲルドの谷エリアの黄金のスタルチュラ４匹",
    "All 4 Lon Lon Ranch area Skulltulas":
      "ロンロン牧場エリアの黄金のスタルチュラ４匹",
    "All 4 Lost Woods area Skulltulas":
      "迷いの森エリアの黄金のスタルチュラ４匹",
    "All 4 Market area Skulltulas": "城下町エリアの黄金のスタルチュラ４匹",
    "All 4 Skulltulas in Deku Tree": "デクの樹様の中の黄金のスタルチュラ４匹",
    "All 4 Skulltulas in Jabu-Jabu":
      "ジャブジャブ様のお腹の黄金のスタルチュラ４匹",
    "All 4 Wasteland/ Colossus area Skulltulas":
      "幻影の砂漠・巨大邪神像エリアの黄金のスタルチュラ４匹",
    "All 5 Child Death Mountain area Skulltulas":
      "デスマウンテンエリアの黄金のスタルチュラ５匹",
    "All 5 Lake Hylia Skulltulas": "ハイリア湖畔エリアの黄金のスタルチュラ５匹",
    "All 5 Skulltulas in Dodongo's Cavern":
      "ドドンゴの洞窟の黄金のスタルチュラ５匹",
    "All 5 Skulltulas in Fire Temple": "炎の神殿の黄金のスタルチュラ５匹",
    "All 5 Skulltulas in Forest Temple": "森の神殿の黄金のスタルチュラ５匹",
    "All 5 Skulltulas in Shadow Temple": "闇の神殿の黄金のスタルチュラ５匹",
    "All 5 Skulltulas in Spirit Temple": "魂の神殿の黄金のスタルチュラ５匹",
    "All 5 Skulltulas in Water Temple": "水の神殿の黄金のスタルチュラ５匹",
    "All 7 Child Kakariko area Skulltulas":
      "カカリコ村エリアの黄金のスタルチュラ７匹",
    "All 8 Death Mountain area Skulltulas":
      "デスマウンテンエリアの黄金のスタルチュラ８匹",
    "All 8 Kakariko area Skulltulas":
      "カカリコ村エリアの黄金のスタルチュラ８匹",
    "All 8 Skulltulas in Bottom of the Well & Shadow Temple": "井戸の底の黄金、闇の神殿の黄金のスタルチュラ8匹",
    "All 8 Skulltulas in Ice Cavern & Spirit Temple": "氷の洞窟の黄金、魂の神殿の黄金のスタルチュラ8匹",
    "All 8 Zora's Domain area Skulltulas":
      "ゾーラの里エリアの黄金のスタルチュラ８匹",
    "All 9 Soft Soil Skulltulas": "フワっとした土から現れる黄金のスタルチュラ9匹",
    "Beat Dodongo's Cavern": "ドドンゴの洞窟クリア",
    "Beat Dodongo's Cavern & Fire Temple": "ドドンゴの洞窟クリア、炎の神殿クリア",
    "Beat Jabu-Jabu's Belly": "ジャブジャブ様のお腹クリア",
    "Beat Jabu-Jabu's Belly & Water Temple": "ジャブジャブ様のお腹クリア、水の神殿クリア",
    "Beat the Deku Tree": "デクの樹様の中クリア",
    "Beat the Deku Tree & Forest Temple": "森の神殿クリア",
    "Beat the Fire Temple": "炎の神殿クリア",
    "Beat the Forest Temple": "森の神殿クリア",
    "Beat the Shadow Temple": "闇の神殿クリア",
    "Beat the Spirit Temple": "魂の神殿クリア",
    "Beat the Water Temple": "水の神殿クリア",
    "Biggoron's Sword": "ダイゴロン刀",
    "Blue Fire": "青い炎",
    "Blue Gauntlets": "青のグローブ",
    "Blue Potion": "青いクスリ",
    "Bolero of Fire": "炎のボレロ",
    "Bomb Bag (30)": "ボム袋（３&#8288;０）",
    Boomerang: "ブーメラン",
    "Both Child Gerudo Valley area Skulltulas":
      "ゲルドの谷エリアの黄金のスタルチュラ２匹",
    "Both Child Kokiri Forest area Skulltulas":
      "コキリの森エリアの黄金のスタルチュラ２匹",
    "Both Child Lost Woods area Skulltulas":
      "迷いの森エリアの黄金のスタルチュラ２匹",
    "Both Child Wasteland/ Colossus area Skulltulas":
      "幻影の砂漠・巨大邪神像エリアの黄金のスタルチュラ２匹",
    "Both Gerudo Valley HPs": "ゲルドの谷のハートのかけら２つ",
    "Both Gerudo's Fortress area Skulltulas":
      "ゲルドの砦の黄金のスタルチュラ２匹",
    "Both HPs in Death Mountain Crater":
      "デスマウンテン火口のハートのかけら２つ",
    "Both HPs in Lost Woods": "迷いの森のハートのかけら２つ",
    "Both Hyrule Field area Skulltulas":
      "ハイラル平原エリアの黄金のスタルチュラ２匹",
    "Both Rusty Switches in Spirit Temple": "魂の神殿の錆びたスイッチ２つ",
    "Bottled Fairy": "ビン（妖精）",
    "Bottled Poe": "ビン（ポウ）",
    "Bronze Gauntlets": "銅のグローブ",
    "Bullet Bag (40)": "デクのタネ袋（４&#8288;０）",
    "Bullet Bag (50)": "デクのタネ袋（５&#8288;０）",
    "Clear 10 Silver Rupee Rooms": "銀ルピー部屋を１&#8288;０箇所攻略",
    "Clear 4 Silver Rupee Rooms": "銀ルピー部屋を４箇所攻略",
    "Clear 8 Silver Rupee Rooms": "銀ルピー部屋を８箇所攻略",
    "Cow in House": "牛（リンクの家）",
    "Defeat 10 Different Stalfos": "スタルフォスを１&#8288;０体撃破",
    "Defeat 4 Different Iron Knuckles": "アイアンナックを４体撃破",
    "Defeat 5 Different Stalfos": "スタルフォスを５体撃破",
    "Defeat a Skull Kid": "スタルキッド撃破",
    "Defeat a White Wolfos": "ホワイトウルフォス撃破",
    "Defeat all Lizalfos in Dodongo's Cavern":
      "ドドンゴの洞窟のリザルフォス全て撃破",
    "Defeat Amy (Green Poe)": "エイミー撃破（緑のポウ）",
    "Defeat Barinade": "バリネード撃破",
    "Defeat Big Octo": "大オクタ撃破",
    "Defeat Bongo-Bongo": "ボンゴボンゴ撃破",
    "Defeat both Flare Dancers": "フレアダンサー２体撃破",
    "Defeat Dark Link": "ダークリンク撃破",
    "Defeat King Dodongo": "キングドドンゴ撃破",
    "Defeat Meg (Purple Poe)": "メグ撃破（紫のポウ）",
    "Defeat Morpha": "モーファ撃破",
    "Defeat Nabooru-Knuckle": "アイアンナック（ナボール）撃破",
    "Defeat Phantom Ganon": "ファントムガノン撃破",
    "Defeat Queen Gohma": "ゴーマ撃破",
    "Defeat Twinrova": "ツインローバ撃破",
    "Defeat Volvagia": "ヴァルバジア撃破",
    "Desert Colossus HP": "巨大邪神像のハートのかけら",
    "Din's Fire": "ディンの炎",
    "Double Defense": "防御力２倍",
    "Double Magic": "魔力２倍",
    "Epona's Song": "エポナの歌",
    "Exactly 20 Deku Sticks": "デクの棒３&#8288;０本",
    "Exactly 30 Deku Sticks": "デクの棒３&#8288;０本",
    "Fairy Bow": "妖精の弓",
    "Fairy Ocarina": "妖精のオカリナ",
    "Fairy Slingshot": "妖精のパチンコ",
    "Farore's Wind": "フロルの風",
    "Fill 20 Item Inventory Slots":
      "Cアイテムのスロットを３&#8288;０箇所埋める",
    "Fill all 4 Bottle Slots": "４つの空きビンスロットを全て埋める",
    "Fire Arrows": "炎の矢",
    "Fire Medallion": "炎のメダル",
    "Fire Temple Boss Key": "炎の神殿のボス部屋の鍵",
    "Forest Medallion": "森のメダル",
    "Forest Temple Boss Key": "森の神殿のボス部屋の鍵",
    "Free all 9 Gorons in Fire Temple": "炎の神殿で９人のゴロンを全員救う",
    "Frog's HP": "カエルのハートのかけら（嵐の歌）",
    "Ganon's Castle Boss Key": "ガノン城のボス部屋の鍵",
    "Gerudo's Card": "ゲルドの会員証",
    "Get Bombchu chest in Spirit Temple": "魂の神殿のボムチュウ取得",
    "Giant's Knife": "巨人のナイフ",
    "Giant's Wallet": "巨人のサイフ",
    "Golden Gauntlets": "金のグローブ",
    "Golden Scale": "金のウロコ",
    "Goron Bracelet": "ゴロンの腕輪",
    "Goron Tunic": "ゴロンの服",
    "Goron's Ruby": "ゴロンのルビー",
    "Green Gauntlets": "緑のグローブ",
    "Green Potion": "緑のクスリ",
    Hookshot: "フックショット",
    "Ice Arrows": "氷の矢",
    "Ice Cavern HP": "氷の洞窟のハートのかけら",
    "Iron Boots": "ヘビーブーツ",
    "Keaton Mask": "キータンのお面",
    "Kokiri's Emerald": "コキリのヒスイ",
    "Lens of Truth": "まことのメガネ",
    "Light Arrows": "光の矢",
    "Lon Lon Ranch HP": "ロンロン牧場のハートのかけら",
    Longshot: "ロングフック",
    "Lost Dog HP": "リチャードのハートのかけら",
    "Magic Bar": "魔力メーター",
    "Map & Compass in Bottom of the Well": "井戸の底のマップとコンパス",
    "Map & Compass in Deku Tree": "デクの樹様の中のマップとコンパス",
    "Map & Compass in Dodongo's Cavern": "ドドンゴの洞窟のマップとコンパス",
    "Map & Compass in Fire Temple": "炎の神殿のマップとコンパス",
    "Map & Compass in Forest Temple": "森の神殿のマップとコンパス",
    "Map & Compass in Ice Cavern": "氷の洞窟のマップとコンパス",
    "Map & Compass in Jabu-Jabu": "ジャブジャブ様のお腹のマップとコンパス",
    "Map & Compass in Shadow Temple": "闇の神殿のマップとコンパス",
    "Map & Compass in Spirit Temple": "魂の神殿のマップとコンパス",
    "Map & Compass in Water Temple": "水の神殿のマップとコンパス",
    "Megaton Hammer": "メガトンハンマー",
    Milk: "ロンロン牛乳",
    "Minuet of Forest": "森のメヌエット",
    "Mirror Shield": "ミラーシールド",
    "Nayru's Love": "ネールの愛",
    "Obtain 12 Different Heart Pieces":
      "ハートのかけら１&#8288;２個（増殖禁止）",
    "Obtain 16 Different Heart Pieces":
      "ハートのかけら１&#8288;６個（増殖禁止）",
    "Obtain 3 Different Heart Containers": "ハートの器３つ（増殖禁止）",
    "Obtain 4 Different Heart Containers": "ハートの器４つ（増殖禁止）",
    "Obtain all 5 Small Keys in Forest Temple":
      "森の神殿の小さな鍵の宝箱を５つ全て開ける",
    "Obtain all 5 Small Keys in Shadow Temple": "闇の神殿の小さな鍵５つ取得",
    "Obtain all 8 Small Keys in Fire Temple":
      "炎の神殿の小さな鍵の宝箱を８つ全て開ける",
    "Open 2 Boss Key Doors": "ボスカギの扉を２つ開ける",
    "Open 3 Boss Key Doors": "ボスカギの扉を３つ開ける",
    "Open 3 Gold Rupee Chests": "金ルピーの宝箱を３つ開ける",
    "Open 5 Gold Rupee Chests": "金ルピーの宝箱を５つ開ける",
    "Open 50 Rupee chest in Wasteland":
      "幻影の砂漠の５&#8288;０ルピーの宝箱を開ける",
    "Open All 6 Gold Rupee Chests": "金ルピーの宝箱を６つ開ける",
    "Open Forest Temple Boss Key Door": "森の神殿のボスカギの扉を開ける",
    "Open the Final Door of Fire Trial": "炎の結界の最後の部屋に到達",
    "Open the Final Door of Forest Trial": "森の結界の最後の部屋に到達",
    "Open the Final Door of Light Trial": "光の結界の最後の部屋に到達",
    "Open the Final Door of Shadow Trial": "闇の結界の最後の部屋に到達",
    "Open the Final Door of Spirit Trial": "魂の結界の最後の部屋に到達",
    "Open the Final Door of Water Trial": "水の結界の最後の部屋に到達",
    "Plant 3 Magic Beans": "魔法の豆を３ヶ所に埋める",
    "Plant 4 Magic Beans": "魔法の豆を４ヶ所に埋める",
    "Plant 5 Magic Beans": "魔法の豆を５つ植える",
    "Plant 6 Magic Beans": "魔法の豆を６ヶ所に埋める",
    "Plant 7 Magic Beans": "魔法の豆を７ヶ所に埋める",
    "Plant bean in Death Mountain Crater":
      "デスマウンテン火口の土にマメを植える",
    "Quiver (40)": "矢立て（４&#8288;０）",
    "Quiver (50)": "矢立て（５&#8288;０）",
    "Red Potion": "赤いクスリ",
    "Requiem of Spirit": "魂のレクイエム",
    "Ruto's Letter": "ルトの手紙",
    "Saria's Song": "サリアの歌",
    "Shadow Temple Boss Key": "闇の神殿のボス部屋の鍵",
    "Silver Gauntlets": "銀のグローブ",
    "Silver Scale": "銀のウロコ",
    "Skull Mask": "ドクロのお面",
    "Spirit Temple Boss Key": "魂の神殿のボス部屋の鍵",
    "Spooky Mask": "こわそなお面",
    "Stone of Agony": "もだえ石",
    "Two Fairy Spells": "魔法のアイテム２つ",
    "Water Medallion": "水のメダル",
    "Water Temple Boss Key": "水の神殿のボス部屋のカギ",
    "Win Bombchu Bowling Prize": "ボムチュウボウリングの景品を何か１つ入手",
    "Zora Tunic": "ゾーラの服",
    "Zora's Sapphire": "ゾーラのサファイア",

    // Legacy goals
    "2 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ２つ",
    "3 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ３つ",
    "37th heart piece (Child Fortress)":
      "３&#8288;７番目のハートのかけら（子供のゲルドの砦）",
    "4 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ４つ",
    "5 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ５つ",
    "6 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ６つ",
    "Both heart pieces in Death Mountain Crater":
      "デスマウンテン火口のハートのかけら２つ",
    "Both heart pieces in Lost Woods": "迷いの森のハートのかけら２つ",
    "Ocarina of Time": "時のオカリナ",
    "Open 3 gold rupee chests": "",
    "All 4 Adult Skulltulas in Zora's Domain Area":
      "大人時代のゾーラの里エリアの黄金のスタルチュラ４匹",
    "All 4 Child Skulltulas in Zora's Domain Area":
      "子供時代のゾーラの里エリアの黄金のスタルチュラ４匹",
    "Defeat Meg (purple Poe)": "メグ撃破（紫のポウ）",
    "7 Hearts": "ハート７つ",
    "All 4 Lon-Lon Ranch area Skulltulas":
      "ロンロン牧場エリアの黄金のスタルチュラ４匹",
    "Get to the end of Fire Trial": "炎の結界の最後の部屋に到達",
    "Get to the end of Forest Trial": "森の結界の最後の部屋に到達",
    "Get to the end of Light Trial": "光の結界の最後の部屋に到達",
    "Get to the end of Shadow Trial": "闇の結界の最後の部屋に到達",
    "Get to the end of Spirit Trial": "魂の結界の最後の部屋に到達",
    "Get to the end of Water Trial": "水の結界の最後の部屋に到達",
    "2 Lon Lon Ranch Area Skulltulas":
      "ロンロン牧場エリアの黄金のスタルチュラ２匹",
    "5 Zora Area HPs": "ゾーラエリアのハートのかけら５つ",
    "8 Hearts (No Duping)": "ハート８つ（複製禁止）",
    "9 Hearts (No Duping)": "ハート９つ（複製禁止）",
    "All 3 Kokiri Forest Area Skulltulas":
      "コキリの森エリアの黄金のスタルチュラ３匹",
    "All 4 Gerudo Valley Area Skulltulas":
      "ゲルドの谷エリアの黄金のスタルチュラ４匹",
    "All 4 Lon Lon Ranch Area Skulltulas":
      "ロンロン牧場エリアの黄金のスタルチュラ４匹",
    "All 4 Lost Woods Area Skulltulas":
      "迷いの森エリアの黄金のスタルチュラ４匹",
    "All 4 Market Area Skulltulas": "城下町エリアの黄金のスタルチュラ４匹",
    "All 4 Wasteland/ Colossus Area Skulltulas":
      "幻影の砂漠・巨大邪神像エリアの黄金のスタルチュラ４匹",
    "All 8 Death Mountain Area Skulltulas":
      "デスマウンテンエリアの黄金のスタルチュラ８匹",
    "All 8 Kakariko Area Skulltulas":
      "カカリコ村エリアの黄金のスタルチュラ８匹",
    "All 8 Zora's Domain Area Skulltulas":
      "ゾーラの里エリアの黄金のスタルチュラ８匹",
    "Both Gerudo's Fortress Area Skulltulas":
      "ゲルドの砦の黄金のスタルチュラ２匹",
    "Both Hyrule Field Area Skulltulas":
      "ハイラル平原エリアの黄金のスタルチュラ２匹",
    "Plant Bean in Death Mountain Crater":
      "デスマウンテン火口の土にマメを植える",
    "All 4 Adult Skulltulas in Zora's Domain":
      "大人時代のゾーラの里エリアの黄金のスタルチュラ４匹",
    "All 4 Child Skulltulas in Zora's Domain":
      "子供時代のゾーラの里エリアの黄金のスタルチュラ４匹",
    "8 Hearts": "ハート８つ",
    "9 Hearts": "ハート９つ",
    "1 unused small key in each Adult Dungeon":
      "全ての大人のダンジョンから未使用の鍵最低１つずつ",
    "3 songs": "歌３つ以上",
    "7 different unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵７つ（増殖禁止）",
    "8 different unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵８つ（増殖禁止）",
    "Free all 9 gorons in Fire Temple": "炎の神殿で９人のゴロンを全員救う",
    "Frog's Heart Piece": "カエルのハートのかけら（嵐の歌）",
    "Ice Cavern Heart Piece": "氷の洞窟のハートのかけら",
    "Zora's Saphire": "ゾーラのサファイア",
    "15 Unique Skulltulas": "スタルチュラのしるし１&#8288;５個（増殖禁止）",
    "9 different unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用の鍵９つ（増殖禁止）",
    "At Least 1 Skulltula from each Adult Dungeon":
      "全ての大人ダンジョンからスタルチュラ最低１匹ずつ",
    "At Least 1 Skulltula from each Child Dungeon":
      "全ての子供ダンジョンからスタルチュラ最低１匹ずつ",
    "At least 1 unused key in each Adult Dungeon":
      "全ての大人のダンジョンから未使用の鍵最低１つずつ",
    "At least 10 songs": "歌１&#8288;０つ以上",
    "At Least 3 Lake Hylia Skulltulas":
      "ハイリア湖畔エリアの黄金のスタルチュラ３匹以上",
    "At least 3 Skulltulas in Water Temple":
      "水の神殿の黄金のスタルチュラ３匹以上",
    "At least 3 songs": "歌３つ以上",
    "At least 30 Deku Nuts": "デクの実３&#8288;０個以上",
    "At least 4 Skulltulas in Shadow Temple":
      "闇の神殿の黄金のスタルチュラ４匹以上",
    "At least 4 songs": "歌４つ以上",
    "At Least 5 Magic Beans": "魔法のマメ５つ以上",
    "At Least 5 Zora Area HPs": "ゾーラエリアのハートのかけら５つ以上",
    "At least 6 songs": "歌６つ以上",
    "At least 7 Magic Beans": "魔法のマメ７つ以上",
    "At Least 7 Songs": "歌７つ以上",
    "At least 8 songs": "歌８つ以上",
    "At least 9 Magic Beans": "魔法のマメ９つ以上",
    "At least 9 songs": "歌９つ以上",
    "Defeat 4 Iron Knuckles": "アイアンナックを４体撃破",
    "Fire Arrow": "炎の矢",
    "Open all 5 Small Key chests in Forest Temple":
      "森の神殿の小さな鍵の宝箱を５つ全て開ける",
    "Open all 5 Small Key chests in Shadow Temple":
      "闇の神殿の小さな鍵５つ取得",
    "Open all 8 Small Key chests in Fire Temple":
      "炎の神殿の小さな鍵の宝箱を８つ全て開ける",
    "Bombchu Bowling Heart Piece": "ボムチュウボウリングのハートのかけら",
    "Get to the end of the Forest Trial": "森の結界の最後の部屋に到達",
    "Bottled Big Poe": "ビン（ビッグポウ）",
    "8 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ８つ",
    "At least 5 songs": "歌５つ以上",
    "Black Gauntlets": "黒のグローブ",
    "Bottled Fish": "ビン（魚）",
    "Bunny Hood": "ウサギずきん",
    "Prelude of Light": "光のプレリュード",
    "Serenade of Water": "水のセレナーデ",
    "Treasure Chest Game Heart Piece": "宝箱ゲームのハートのかけら",
    "7 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ７つ",
    "At least 4 Skulltulas in Water Temple":
      "水の神殿の黄金のスタルチュラ４匹以上",
    "10 Hearts": "ハート１&#8288;０個",
    "4 Boss Keys": "ボス部屋のカギ４つ",
    "9 unused keys in Gerudo Training Grounds":
      "ゲルドの修練場の未使用のカギ９つ",
    "At least 7 songs": "歌７つ以上",
    "Biggoron窶冱 Sword": "ダイゴロン刀",
    "Bomb Bag (40)": "ボム袋（４&#8288;０）",
    "Broken Goron's Sword": "折れたゴロン刀（トレードアイテム）",
    "Claim Check": "ひきかえ券",
    Cojiro: "コジロー",
    "Defeat Ganon": "ガノン撃破",
    "Odd Potion": "あやしいクスリ",
    "Poacher's Saw": "密猟者のノコギリ",
    "Pocket Cucco": "てのりコッコ",
    Prescription: "処方箋",
    "3 Swords": "剣３種類",
    "Defeat both Dead-Hands": "デドハンド２体撃破",
    "Never obtain Bombchus": "ボムチュウ未取得",
    "Never obtain Hookshot": "フックショット未取得",
    "Never save": "セーブ未使用",
    "Nocturne of Shadow": "闇のノクターン",
    "Obtain the Bombchu chest in Ganon's Castle":
      "ガノン城の宝箱からボムチュウ取得",
    "50 Bombchus": null,
    "At least 20 Deku Sticks": null,
    "37th heart piece (Fortress)": null,
    "All Death Mountain area Skulltulas": null,
    "All Gerudo Fortress area Skulltulas": null,
    "All Gerudo Valley area Skulltulas": null,
    "All Hyrule Field area Skulltulas": null,
    "All Kakariko area Skulltulas": null,
    "All Kokiri Forest area Skulltulas": null,
    "All Lake Hylia Skulltulas": null,
    "All Lon-Lon Ranch area Skulltulas": null,
    "All Lost Woods area Skulltulas": null,
    "All Market area Skulltulas": null,
    "All Skulltulas in Bottom of the Well": null,
    "All Skulltulas in Deku Tree": null,
    "All Skulltulas in Dodongo's Cavern": null,
    "All Skulltulas in Fire Temple": null,
    "All Skulltulas in Forest Temple": null,
    "All Skulltulas in Ice Cavern": null,
    "All Skulltulas in Jabu-Jabu": null,
    "All Skulltulas in Shadow Temple": null,
    "All Skulltulas in Spirit Temple": null,
    "All Skulltulas in Water Temple": null,
    "All Zora's Domain area Skulltulas": null,

    // UI
    " / ": "・",
    ": Boss keys for child dungeons obtained through RBA count": null,
    ": Ice Cavern and Jabu-Jabu do not count": null,
    ": Item must display visually in inventory to count": null,
    ": Only dungeons with blue warps are required": null,
    ": Only one of the frog's HPs is required": null,
    ": Planting multiple beans in the same location (e.g. by duping soft soil patches) is not allowed":
      null,
    ": Scarecrow's Song does not count": null,
    ": Using RBA to write Heart Pieces into the inventory does not count as duping and is allowed":
      null,
    About: null,
    "All required items must be present in the inventory in order to finish. For example, for the goal <i>Blue Potion</i>, you must not drink it":
      null,
    "Arbitrary Code Execution (ACE)": null,
    "BL-TR": "左下右上",
    BOARD: "ボード",
    "Banned Tricks": null,
    "Beat Dungeon: When you step in the blue warp and lose control or skip the cutscene":
      null,
    "Defeat an Enemy: When you strike the last blow and the death animation completes. If defeating the enemy is permanent, when the associated cutscene begins": null,
    "Defeat a Boss: When you strike the last blow and the death cutscene begins": null,
    "Blackout card": null,
    COL1: "列１",
    COL2: "列２",
    COL3: "列３",
    COL4: "列４",
    COL5: "列５",
    Credits: null,
    "Filename:": "ファイル名：",
    "Get Item Manipulation (GIM)": null,
    "Goal Clarifications": null,
    "If Wrong Warping, any items or goals associated with the wrong warp are obtained upon completion of the Wrong Warp":
      null,
    "Item: When you are holding it above your head": null,
    "Jumpslash Quick Putaway (QPA)": null,
    "Mode:": "モード：",
    "Normal card": null,
    "Numbers are minimums. Collecting more than enough is allowed unless otherwise stated":
      null,
    "Obtaining the Eyeball Frog without presenting the Prescription (Hold R)":
      null,
    "Ocarina of Time Bingo": "時のオカリナビンゴ",
    "Other Rules": null,
    "Other versions": null,
    ROW1: "行１",
    ROW2: "行２",
    ROW3: "行３",
    ROW4: "行４",
    ROW5: "行５",
    Rules: null,
    "Seed:": "シード：",
    Settings: null,
    "Short card": null,
    'Song: When the dialog box that says "You have learned the…" completes':
      null,
    "Stale Reference Manipulation (SRM)": null,
    "TL-BR": "左上右下",
    "The goals are balanced around playing on the Japanese version of Ocarina of Time":
      null,
    "This is a <i>Bingo</i> board for Ocarina of Time races": null,
    "To win, you must complete 5 of the tasks in a row horizontally, vertically, or diagonally":
      null,
    "Unlike in most speedrunning categories, the intro cutscene should not be skipped. This gives players a few minutes to plan":
      null,
    "Using Bombchus out of bounds": null,
    "Using Deku Stick as adult": null,
    "Version:": "バージョン：",
    "When an item may be marked as completed:": null,
    X: "Ｘ",
    "You can click on the squares to turn them green and red. This may help you organize your route planning":
      null,
    "The page you are looking for does not exist": null,
    "Show All Versions": null,
  },
};
