export const goals = [
  "Silver Gauntlets",
  "Ice Arrow",
  "Milk",
  "Fairy Bow",
  "Mask of Truth",
  "Blue Fire",
  "Nayru's Love",
  "Goron's Ruby",
  "Bottled Big Poe",
  "Stone of Agony",
  "Farore's Wind",
  "Goron Bracelet",
  "Water Medallion",
  "Fire Arrow",
  "Quiver (50)",
  "Silver Scale",
  "Fire Medallion",
  "Light Arrow",
  "Red Potion",
  "Mirror Shield",
  "Iron Boots",
  "Claim Check",
  "Zora Tunic",
  "Forest Medallion",
  "Prelude of Light",
  "Nocturne of Shadow",
  "Gerudo's Card",
  "Lens of Truth",
  "Kokiri's Emerald",
  "Golden Gauntlets",
  "Boomerang",
  "Din's Fire",
  "Adult's Wallet",
  "Hover Boots",
  "Magic Bean",
  "Green Potion",
  "Goron Tunic",
  "Spirit Medallion",
  "Longshot",
  "Slingshot",
  "Bomb Bag (40)",
  "Serenade of Water",
  "Ocarina of Time",
  "Minuet of Forest",
  "Megaton Hammer",
  "Bolero of Fire",
  "Shadow Medallion",
  "Giant's Wallet",
  "Blue Potion",
];
